/* Beau's Game Inventory — local admin panel */
(function(){
'use strict';
const KEY='beauAdminPinHash',SET='beauAdminSettings';
const getInv=()=>{try{const x=JSON.parse(localStorage.getItem('resellerInventory')||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}};
function page(){return document.getElementById('page-settings')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function hash(v){if(window.crypto?.subtle){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}return btoa(v)}
function panel(){if(document.getElementById('adminPanel'))return;const p=page();if(!p)return;const s=document.createElement('section');s.className='panel';s.id='adminPanel';s.innerHTML=`<h2>🔐 Admin Panel</h2><p>Local administrator controls for this device.</p><div id="adminLock"><div class="price-box"><h3>🔒 Admin Access</h3><p id="adminLockText">Set an admin PIN to protect this panel.</p><input id="adminPin" type="password" inputmode="numeric" maxlength="8" placeholder="4–8 digit PIN"><div class="actions"><button class="primary" id="adminUnlock">Set PIN</button></div></div></div><div id="adminTools" style="display:none"><div class="price-box"><h3>📊 System Overview</h3><div id="adminStats"></div></div><div class="price-box"><h3>⚙️ Pricing Rules</h3><label>Maximum buy percentage<input id="adminBuyPct" type="number" min="1" max="100" step="1"></label><div class="actions"><button class="success" id="adminSaveRules">Save Pricing Rules</button></div></div><div class="price-box"><h3>💾 Data Management</h3><div class="actions"><button class="secondary" id="adminBackup">Export Backup</button><button class="danger" id="adminResetPrefs">Reset App Preferences</button></div></div><div class="price-box"><h3>🧪 Diagnostics</h3><div id="adminDiag"></div><div class="actions"><button class="secondary" id="adminLockBtn">🔒 Lock Admin</button></div></div></div>`;p.appendChild(s);wire()}
function wire(){const pin=document.getElementById('adminPin'),unlock=document.getElementById('adminUnlock');unlock.onclick=async()=>{const v=pin.value.trim();if(!/^\d{4,8}$/.test(v)){alert('Use a 4–8 digit PIN.');return}const h=await hash(v),old=localStorage.getItem(KEY);if(old&&old!==h){alert('Incorrect PIN.');return}localStorage.setItem(KEY,h);pin.value='';unlock.textContent='Unlock Admin';open()};document.getElementById('adminLockBtn').onclick=lock;document.getElementById('adminSaveRules').onclick=()=>{const n=Number(document.getElementById('adminBuyPct').value||70);localStorage.setItem(SET,JSON.stringify({buyPct:Math.min(100,Math.max(1,n))}));alert('Pricing rules saved.')};document.getElementById('adminBackup').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([localStorage.getItem('resellerInventory')||'[]'],{type:'application/json'}));a.download='beaus-inventory-backup.json';a.click()};document.getElementById('adminResetPrefs').onclick=()=>{if(confirm('Reset app preferences? Inventory will not be deleted.')){localStorage.removeItem('beauDarkMode');localStorage.removeItem('resellerDarkMode');localStorage.removeItem('beauLastScreenHash');alert('Preferences reset.')}}}
function open(){document.getElementById('adminLock').style.display='none';document.getElementById('adminTools').style.display='block';const inv=getInv(),units=inv.reduce((a,i)=>a+Number(i.quantity||0),0),cost=inv.reduce((a,i)=>a+Number(i.cost||0)*Number(i.quantity||0),0);document.getElementById('adminStats').innerHTML=`<div class="price-row"><span>Inventory records</span><strong>${inv.length}</strong></div><div class="price-row"><span>Stock units</span><strong>${units}</strong></div><div class="price-row"><span>Stock cost</span><strong>$${cost.toFixed(2)}</strong></div>`;let cfg={};try{cfg=JSON.parse(localStorage.getItem(SET)||'{}')}catch(e){}document.getElementById('adminBuyPct').value=cfg.buyPct||70;document.getElementById('adminDiag').innerHTML='<div class="price-row"><span>Local storage</span><strong>✅ Available</strong></div><div class="price-row"><span>OTA updater</span><strong>✅ '+esc(window.BeauUpdate?.version||'Unknown')+'</strong></div><div class="price-row"><span>Inventory data</span><strong>✅ '+inv.length+' records</strong></div>'}
function lock(){document.getElementById('adminTools').style.display='none';document.getElementById('adminLock').style.display='block';document.getElementById('adminLockText').textContent='Enter your admin PIN to unlock.';document.getElementById('adminUnlock').textContent='Unlock Admin'}
function init(){setTimeout(panel,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.addEventListener('beau:update-ready',init)})();
