/* Beau's Game Inventory navigation — stable direct-link build v5.2.0 */
(function(){
'use strict';
const items=[['Dashboard','dashboard'],['Inventory','inventory'],['Scanner','scanner'],['Pricing','pricing'],['Library','library'],['Settings','settings']];
const svg={dashboard:'📊',inventory:'📦',scanner:'📷',pricing:'💰',library:'📚',settings:'⚙️'};
const pages={};
function getContainer(){return document.querySelector('.container')}
function pageForPanel(panel){const t=(panel.querySelector('h2')?.textContent||'').trim().toLowerCase();if(t.includes('quick sale')||t.includes('sales history')||t.includes('record sale')||t==='sales'||t.includes('sell inventory')){panel.remove();return null}if(t.includes('barcode scanner')||t.includes('scanner'))return 'scanner';if(t.includes('price comparison')||t.includes('pricing')||t.includes('market price'))return 'pricing';if(t.includes('library')||t.includes('scanned games'))return 'library';if(t.includes('backup')||t.includes('settings')||t.includes('appearance')||t.includes('updates'))return 'settings';if(t.includes('add / edit item')||t==='📦 inventory'||t.includes('inventory'))return 'inventory';return null}
function buildPages(){const c=getContainer();if(!c)return;if(c.querySelector(':scope > .app-page')){cachePages();return}const buckets={dashboard:[],inventory:[],scanner:[],pricing:[],library:[],settings:[]};const d=c.querySelector(':scope > .dashboard');if(d)buckets.dashboard.push(d);[...c.querySelectorAll(':scope > .panel')].forEach(p=>{const k=pageForPanel(p);if(k)buckets[k].push(p)});Object.entries(buckets).forEach(([k,els])=>{const p=document.createElement('main');p.className='app-page';p.id='page-'+k;els.forEach(e=>p.appendChild(e));c.appendChild(p)});cachePages()}
function cachePages(){items.forEach(([,k])=>pages[k]=document.getElementById('page-'+k))}
function addAdminSettings(){const p=pages.settings;if(!p||document.getElementById('adminSettingsPanel'))return;const s=document.createElement('section');s.className='panel';s.id='adminSettingsPanel';s.innerHTML=`<h2>🛠️ Admin Settings</h2><p>Advanced controls for managing Beau's Game Inventory.</p><div class="form-grid"><div><label>App Version</label><input id="adminAppVersion" value="5.2.0" readonly></div><div><label>Storage Used</label><input id="adminStorageInfo" value="Calculating…" readonly></div></div><div class="actions"><button class="secondary" type="button" id="adminRefreshStorage">🔄 Refresh Storage</button><button class="secondary" type="button" id="adminClearCache">🧹 Clear App Cache</button><button class="secondary" type="button" id="adminExportAll">📤 Export All Data</button></div><div class="actions"><button class="danger" type="button" id="adminResetLibrary">🗑️ Clear Game Library</button><button class="danger" type="button" id="adminResetInventory">🗑️ Clear Inventory</button></div><div id="adminStatus" class="source-note" style="margin-top:10px"></div>`;p.appendChild(s);const info=()=>{let bytes=0;for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';bytes+=k.length+(localStorage.getItem(k)||'').length}document.getElementById('adminStorageInfo').value=(bytes/1024).toFixed(1)+' KB'};const msg=t=>{const e=document.getElementById('adminStatus');if(e)e.textContent=t};document.getElementById('adminRefreshStorage').onclick=info;document.getElementById('adminClearCache').onclick=async()=>{try{if('caches'in window){const ks=await caches.keys();await Promise.all(ks.map(k=>caches.delete(k)))}if(navigator.serviceWorker)await Promise.all((await navigator.serviceWorker.getRegistrations()).map(r=>r.update()));msg('App cache cleared. Reload the app to load the latest files.')}catch(e){msg('Cache clear failed: '+e.message)}};document.getElementById('adminExportAll').onclick=()=>{const data={exportedAt:new Date().toISOString(),inventory:JSON.parse(localStorage.getItem('resellerInventory')||'[]'),library:JSON.parse(localStorage.getItem('beauGameLibrary')||'[]')};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='beau-game-inventory-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);msg('All inventory and library data exported.')};document.getElementById('adminResetLibrary').onclick=()=>{if(confirm('Clear the saved game library? This does not remove your inventory.')){localStorage.removeItem('beauGameLibrary');msg('Game library cleared.')}};document.getElementById('adminResetInventory').onclick=()=>{if(confirm('Clear ALL inventory data? This cannot be undone unless you have a backup.')){localStorage.removeItem('resellerInventory');msg('Inventory cleared. Reload the app to refresh dashboard totals.')}};info()}
function activate(k){if(!pages[k])k='dashboard';items.forEach(([,name])=>{const p=pages[name];if(p)p.classList.toggle('active',name===k)});document.querySelectorAll('.mobile-nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===k));history.replaceState(null,'','#'+k)}
function mount(){buildPages();addAdminSettings();document.querySelectorAll('.mobile-nav,.app-shell-nav,.nav').forEach(n=>n.remove());const n=document.createElement('nav');n.className='mobile-nav';n.innerHTML=items.map(([label,k])=>`<button type="button" data-screen="${k}" aria-label="${label}"><span class="icon" style="font-size:21px;line-height:22px">${svg[k]}</span><span class="label">${label}</span></button>`).join('');document.body.appendChild(n);n.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.screen;if(k==='scanner'){window.location.assign('./scanner-v3.html?v=3.2.2');return}if(k==='library'){window.location.assign('./library-v3.html?v=5.1.0');return}activate(k)}));window.BeauNavigation={activate,current:null};const hash=(location.hash||'').replace('#','').split('?')[0];activate(items.some(x=>x[1]===hash)?hash:'dashboard')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
