/* Beau's Game Inventory v1.6.7 — professional reseller tools */
(function(){
'use strict';
const money=v=>'$'+Number(v||0).toFixed(2);
const inv=()=>{try{const x=JSON.parse(localStorage.getItem('resellerInventory')||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
function style(){if(document.getElementById('proStyle'))return;const s=document.createElement('style');s.id='proStyle';s.textContent=`.pro-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.pro-stat{padding:12px;border:1px solid #e5e7eb;border-radius:12px;background:#f8fafc}.pro-stat small{display:block;color:#6b7280;font-weight:700}.pro-stat strong{display:block;font-size:20px;margin-top:4px}.pro-filter{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.age-good{color:#16a34a;font-weight:700}.age-warn{color:#b45309;font-weight:700}.age-bad{color:#dc2626;font-weight:700}@media(max-width:700px){.pro-grid,.pro-filter{grid-template-columns:1fr}}body.dark-mode .pro-stat{background:#1f2937;border-color:#374151}`;document.head.appendChild(s)}
function page(id){return document.getElementById('page-'+id)}
function ageDays(i){const d=Date.parse(i.dateAdded||'');return isNaN(d)?0:Math.max(0,Math.floor((Date.now()-d)/86400000))}
function dashboard(){const p=page('dashboard');if(!p||document.getElementById('proDashboard'))return;const b=document.createElement('section');b.className='panel';b.id='proDashboard';b.innerHTML='<h2>📈 Performance</h2><div class="pro-grid" id="proStats"></div><div id="proPlatforms"></div>';p.appendChild(b);refresh()}
function refresh(){const box=document.getElementById('proStats');if(!box)return;const a=inv();let cost=0,value=0,sales=0,revenue=0,profit=0,units=0;const plat={};a.forEach(i=>{const q=Number(i.quantity||0);units+=q;cost+=q*Number(i.cost||0);value+=q*Number(i.marketPrice||i.selling||i.rrp*.75||0);plat[i.platform||'Other']=(plat[i.platform||'Other']||0)+q;(i.sales||[]).forEach(s=>{const r=Number(s.revenue||s.price||0),f=Number(s.fees||0),p=Number(s.postage||0),c=Number(s.cost||i.cost||0)*Number(s.quantity||1);sales+=Number(s.quantity||1);revenue+=r;profit+=r-f-p-c})});box.innerHTML=[['Stock cost',money(cost)],['Stock value',money(value)],['Potential profit',money(value-cost)],['Units sold',sales],['Revenue',money(revenue)],['Actual profit',money(profit)],['Profit margin',revenue?((profit/revenue)*100).toFixed(1)+'%':'0%'],['Inventory items',a.length]].map(x=>`<div class="pro-stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');const rows=Object.entries(plat).sort((x,y)=>y[1]-x[1]);document.getElementById('proPlatforms').innerHTML=rows.length?'<h3>Platform Stock</h3>'+rows.map(x=>`<div class="price-row"><span>${esc(x[0])}</span><strong>${x[1]} units</strong></div>`).join(''):''}
function inventory(){const p=page('inventory');if(!p||document.getElementById('proInventory'))return;const b=document.createElement('section');b.className='panel';b.id='proInventory';b.innerHTML='<h2>🧰 Inventory Filters</h2><div class="pro-filter"><select id="proPlatform"><option value="">All platforms</option></select><select id="proCategory"><option value="">All categories</option></select><select id="proCondition"><option value="">All conditions</option></select><select id="proAge"><option value="">Any stock age</option><option value="30">30+ days</option><option value="60">60+ days</option><option value="90">90+ days</option></select></div><div class="actions"><button class="primary" id="proFilterApply">🔎 Apply Filters</button><button class="secondary" id="proExportCsv">📄 Export CSV</button></div><div id="proFilterResult"></div>';p.insertBefore(b,p.firstChild);fill();document.getElementById('proFilterApply').onclick=apply;document.getElementById('proExportCsv').onclick=csv}
function fill(){const a=inv();[['proPlatform','platform'],['proCategory','category'],['proCondition','condition']].forEach(([id,k])=>{const s=document.getElementById(id);if(!s)return;[...new Set(a.map(i=>i[k]).filter(Boolean))].sort().forEach(v=>s.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`))})}
function apply(){const a=inv(),pl=document.getElementById('proPlatform').value,ca=document.getElementById('proCategory').value,co=document.getElementById('proCondition').value,ag=Number(document.getElementById('proAge').value||0);const r=a.filter(i=>(!pl||i.platform===pl)&&(!ca||i.category===ca)&&(!co||i.condition===co)&&(!ag||ageDays(i)>=ag));document.getElementById('proFilterResult').innerHTML=r.length?r.map(i=>{const age=ageDays(i);const cls=age>=90?'age-bad':age>=60?'age-warn':'age-good';return `<div class="item"><div class="item-name">${esc(i.name)}</div><p>${esc(i.platform||'Other')} • ${esc(i.category||'Other')} • Qty ${Number(i.quantity||0)}</p><p class="${cls}">Stock age: ${age} days</p><div class="price-row"><span>Cost</span><strong>${money(i.cost)}</strong></div><div class="price-row"><span>Market</span><strong>${money(i.marketPrice||i.selling||0)}</strong></div></div>`}).join(''):'<div class="empty">No items match these filters.</div>'}
function csv(){const rows=[['Name','Barcode','Category','Platform','Condition','Quantity','Cost','RRP','Market Price','Selling Price','Stock Age Days']];inv().forEach(i=>rows.push([i.name,i.barcode,i.category,i.platform,i.condition,i.quantity,i.cost,i.rrp,i.marketPrice,i.selling,ageDays(i)]));const text=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),blob=new Blob([text],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='beaus-game-inventory.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function pricing(){const p=page('pricing');if(!p||document.getElementById('proPricing'))return;const b=document.createElement('section');b.className='panel';b.id='proPricing';b.innerHTML='<h2>🎯 Pricing Rules</h2><p>Use your maximum buy percentage to quickly judge a deal.</p><label>Maximum buy % of resale<input id="proBuyPct" type="number" min="1" max="100" value="70"></label><div id="proRuleResult" class="price-box" style="margin-top:10px"></div>';p.appendChild(b);document.getElementById('proBuyPct').oninput=rule;rule()}
function rule(){const pct=Number(document.getElementById('proBuyPct')?.value||70),m=Number(document.getElementById('marketPrice')?.value||0),r=Number(document.getElementById('rrp')?.value||0),c=Number(document.getElementById('cost')?.value||0),res=m||r*.75,buy=res*pct/100,el=document.getElementById('proRuleResult');if(!el)return;el.innerHTML=`<div class="price-row"><span>Suggested resale</span><strong>${money(res)}</strong></div><div class="price-row"><span>Maximum buy</span><strong>${money(buy)}</strong></div><div class="price-row"><span>Your cost</span><strong>${money(c)}</strong></div><div class="price-row"><span>Estimated profit</span><strong>${money(res-c)}</strong></div>`}
function init(){style();setTimeout(()=>{dashboard();inventory();pricing();refresh()},120)}
window.addEventListener('beau:update-ready',init);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
