/* Beau's Reseller Hub — OTA updater v9.3.3 */
(function(){
'use strict';
const KEY='beauGameInventoryWebVersion',CURRENT='9.3.3',WEB_REV='2026.08.15.11',UPDATE_URL='./update.json',OTA_URL='./ota.html',SCANNER_FIX_URL='./scanner-fix.js',CAMERA_FIX_URL='./scanner-runtime-fix.js',COMPAT_URL='./app-compat.js',CLOUD_LIBRARY_URL='./cloud-library.js',AUTH_CLOUD_URL='./auth-cloud.js';
function compare(a,b){const aa=String(a||'0').replace(/^v/i,'').split(/[.-]/).map(x=>Number(x)||0),bb=String(b||'0').replace(/^v/i,'').split(/[.-]/).map(x=>Number(x)||0);for(let i=0;i<Math.max(aa.length,bb.length);i++){const x=aa[i]||0,y=bb[i]||0;if(x!==y)return x-y}return 0}
function loadScript(url,attr){const old=document.querySelector('script['+attr+']');if(old)old.remove();const s=document.createElement('script');s.src=url+'?v='+Date.now();s.async=false;s.setAttribute(attr,'1');document.head.appendChild(s)}
async function clearOldCaches(){try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}}catch(_){}
}
async function check(){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(UPDATE_URL+'?t='+Date.now(),{cache:'no-store',headers:{'Cache-Control':'no-cache'},signal:c.signal});if(!r.ok)throw Error('Update information unavailable');const d=await r.json(),latest=String(d.version||CURRENT),latestWeb=String(d.webVersion||WEB_REV);return{current:CURRENT,webVersion:WEB_REV,latest,latestWeb,available:compare(latest,CURRENT)>0||compare(latestWeb,WEB_REV)>0,notes:d.message||'',url:d.url||OTA_URL}}finally{clearTimeout(t)}}
async function reloadLatest(){await clearOldCaches();const u=new URL(OTA_URL,location.href);u.searchParams.set('v',Date.now());u.hash=location.hash||'#dashboard';location.replace(u.toString())}
async function checkAndUpdate(options={}){try{const result=await check();if(result.available){const ok=options.silent?true:confirm('A new Beau\'s Reseller Hub web update is available.\n\nApp '+result.latest+'\nWeb revision '+result.latestWeb+'\n'+(result.notes||'')+'\n\nUpdate now?');if(ok)await reloadLatest()}else if(!options.silent)alert('You are up to date (v'+CURRENT+').');try{localStorage.setItem(KEY,result.latestWeb)}catch(_){}return result}catch(e){if(!options.silent)alert(e.name==='AbortError'?'Update check timed out. You can keep using the current app.':'Could not check for updates right now.');return{current:CURRENT,latest:CURRENT,latestWeb:WEB_REV,available:false,error:e.message}}}
function patchSettings(){const v=document.getElementById('appVersion');if(v)v.textContent=CURRENT;const b=document.getElementById('checkUpdate');if(b&&!b.dataset.cloudUpdater){const n=b.cloneNode(true);b.replaceWith(n);n.dataset.cloudUpdater='1';n.addEventListener('click',()=>checkAndUpdate())}}
window.BeauUpdate={version:CURRENT,webVersion:WEB_REV,check,reloadLatest,checkAndUpdate};try{localStorage.setItem(KEY,WEB_REV)}catch(_){}
document.addEventListener('DOMContentLoaded',()=>{loadScript(SCANNER_FIX_URL,'data-scanner-fix');loadScript(CAMERA_FIX_URL,'data-camera-fix');loadScript(COMPAT_URL,'data-app-compat');loadScript(CLOUD_LIBRARY_URL,'data-cloud-library');loadScript(AUTH_CLOUD_URL,'data-auth-cloud');patchSettings();setTimeout(()=>checkAndUpdate({silent:true}),1200)});
})();
