const APP_VERSION='9.2.0';
const $=id=>document.getElementById(id);
const money=v=>'$'+Math.round(Number(v)||0);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const rates={'New':.30,'Like New':.28,'Used - Good':.25,'Used - Fair':.23,'For Parts':.21};
let inventory=[],library=[],scanner=null,editingId=null,lookupBusy=false;
const fallback={'5902367642372':{title:'Cyberpunk 2077: Ultimate Edition',platform:'PlayStation 5',resale:77,retail:100,source:'Verified Australian barcode fallback'},'5030917298462':{title:'Diablo IV',platform:'PlayStation 5',resale:66,retail:88,source:'Verified Australian barcode fallback'}};
function loadData(){try{inventory=JSON.parse(localStorage.getItem('resellerInventory')||'[]')}catch{inventory=[]}if(!Array.isArray(inventory))inventory=[];try{library=JSON.parse(localStorage.getItem('beauGameLibrary')||'[]')}catch{library=[]}if(!Array.isArray(library))library=[]}
function saveData(){localStorage.setItem('resellerInventory',JSON.stringify(inventory));localStorage.setItem('beauGameLibrary',JSON.stringify(library));renderAll()}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function show(page){const valid=['dashboard','inventory','scanner','pricing','library','settings'];if(!valid.includes(page))page='dashboard';document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const shortcuts=document.querySelector('.hero .actions');if(shortcuts)shortcuts.hidden=page!=='dashboard';history.replaceState(null,'','#'+page);if(page==='dashboard')renderDashboard();if(page==='inventory')renderInventory();if(page==='library')renderLibrary();if(page==='settings')renderSettings();window.scrollTo(0,0)}
function renderDashboard(){const units=inventory.reduce((s,x)=>s+(+x.qty||1),0),cost=inventory.reduce((s,x)=>s+(+x.cost||0)*(+x.qty||1),0),sales=inventory.reduce((s,x)=>s+(+x.sell||0)*(+x.qty||1),0);$('du').textContent=units;$('dc').textContent=money(cost);$('ds').textContent=money(sales);$('dp').textContent=money(sales-cost);$('snapshot').innerHTML=inventory.length?inventory.slice(-5).reverse().map(x=>`<div class="list-item"><div><b>${esc(x.name)}</b><div class="muted">${esc(x.platform||'')}</div></div><b>${money(x.sell)}</b></div>`).join(''):'<div class="empty">No stock yet. Scan a game to get started.</div>'}
function renderInventory(){const q=($('invSearch').value||'').toLowerCase();const a=inventory.filter(x=>`${x.name} ${x.barcode} ${x.platform}`.toLowerCase().includes(q));$('invList').innerHTML=a.length?a.map(x=>`<div class="list-item"><div><b>${esc(x.name)}</b><div><span class="pill">${esc(x.platform||'Other')}</span><span class="pill">Qty ${+x.qty||1}</span></div><div class="muted">Barcode ${esc(x.barcode||'—')} · Cost ${money(x.cost)} · Sell ${money(x.sell)}</div></div><div><button class="btn" onclick="editInventory('${x.id}')">Edit</button> <button class="btn danger" onclick="deleteInventory('${x.id}')">Delete</button></div></div>`).join(''):'<div class="empty">No matching stock.</div>'}
function renderLibrary(){const q=($('libSearch').value||'').toLowerCase();const a=library.filter(x=>`${x.title} ${x.barcode} ${x.platform}`.toLowerCase().includes(q));$('libList').innerHTML=a.length?a.slice().reverse().map(x=>`<div class="list-item"><div><b>${esc(x.title)}</b><div><span class="pill">${esc(x.platform||'')}</span><span class="pill">${esc(x.barcode)}</span></div></div><b>${money(x.resale)}</b></div>`).join(''):'<div class="empty">Your saved game library is empty.</div>'}
function renderSettings(){const bytes=new Blob([JSON.stringify({inventory,library})]).size;$('adminInv').textContent=inventory.length;$('adminLib').textContent=library.length;$('adminSize').textContent=(bytes/1024).toFixed(1)+' KB';$('appVersion').textContent=APP_VERSION}
function renderAll(){renderDashboard();renderInventory();renderLibrary();renderSettings()}
function updatePricing(){const resale=Number($('resale').value)||0,condition=$('condition').value,rec=rates[condition]??.25;$('b21').textContent=money(resale*.21);$('b25').textContent=money(resale*.25);$('b30').textContent=money(resale*.30);$('targetText').textContent=`${condition} · ${Math.round(rec*100)}%`;$('rval').textContent=money(resale);$('rbuy').textContent=money(resale*rec);$('rgp').textContent=money(resale-resale*rec);if(window.BeauSmartBuy?.render)window.BeauSmartBuy.render()}
async function startCamera(){if(scanner)return;const status=$('scanStatus');status.textContent='Requesting camera permission…';status.className='status';try{if(!window.Html5Qrcode)throw Error('Camera library did not load');scanner=new Html5Qrcode('reader');const cams=await Html5Qrcode.getCameras();if(!cams?.length)throw Error('No camera was found');const preferred=cams.find(c=>/back|rear|environment/i.test(c.label))||cams[cams.length-1];await scanner.start(preferred.id,{fps:10,qrbox:{width:280,height:150},aspectRatio:1.7778},code=>{if(!lookupBusy){$('scanCode').value=code;stopCamera();lookupProduct(code)}},()=>{});status.textContent='Camera ready — point it at a game barcode.';status.className='status ok'}catch(e){scanner=null;status.textContent='Camera could not start: '+(e.message||e);status.className='status bad';toast('Camera could not start')}}
async function stopCamera(){if(!scanner)return;try{await scanner.stop();await scanner.clear()}catch{}scanner=null}
function saveLibrary(p){const key=String(p.barcode);if(!library.some(x=>String(x.barcode)===key))library.push({title:p.title,barcode:key,platform:p.platform||'',resale:p.resale||0,retail:p.retail||0,source:p.source||''});localStorage.setItem('beauGameLibrary',JSON.stringify(library))}
async function lookupProduct(code){if(lookupBusy)return;const b=String(code||'').replace(/\D/g,'');if(!b){toast('Enter a barcode first');return}lookupBusy=true;$('lookupBtn').disabled=true;$('scanStatus').textContent='Looking up product…';$('scanStatus').className='status';$('scanResult').innerHTML='<div class="empty">Searching product and pricing…</div>';try{let p=fallback[b]||null;if(!p&&window.BeauPricingEngine){const r=await window.BeauPricingEngine.lookup(b);const n=window.BeauPricingEngine.normalise(r.data,b);if(n.title&&n.title!=='Unknown game')p={title:n.title,platform:n.platform,resale:n.resale,retail:n.retail,source:r.route}}if(!p)throw Error('This barcode was not matched to a game.');p.barcode=b;p.resale=Number(p.resale)||0;p.retail=Number(p.retail)||0;saveLibrary(p);$('scanStatus').textContent='Product found';$('scanStatus').className='status ok';const r=p.resale||p.retail*.75;const b21=Math.round(r*.21),b25=Math.round(r*.25),b30=Math.round(r*.30),b40=Math.round(r*.40);$('scanResult').innerHTML=`<div><h3>🎮 ${esc(p.title)}</h3><div class="muted">${esc(p.platform||'Unknown platform')} · Barcode ${esc(b)}</div><div class="buygrid"><div class="buy"><span>21% CONSERVATIVE</span><strong>${money(b21)}</strong></div><div class="buy recommended"><span>25% RECOMMENDED ⭐</span><strong>${money(b25)}</strong></div><div class="buy"><span>30% TARGET</span><strong>${money(b30)}</strong></div><div class="buy"><span>40% MAXIMUM</span><strong>${money(b40)}</strong></div></div><div class="result"><div class="list-item"><span>Expected resale</span><b>${money(r)}</b></div><div class="list-item"><span>Pricing source</span><b>${esc(p.source||'Lookup')}</b></div></div><div class="toolbar"><button class="btn success" onclick="addScannedToStock(${JSON.stringify(p).replace(/"/g,'&quot;')})">＋ Add to Stock</button><button class="btn" onclick="show('library')">📚 View Library</button></div></div>`;toast('Product found')}catch(e){$('scanStatus').textContent='Lookup failed';$('scanStatus').className='status bad';$('scanResult').innerHTML=`<div class="result"><h3>Product not found</h3><p class="muted">${esc(e.message||'The pricing service did not return usable product data.')}</p><p class="muted">Barcode: ${esc(b)}</p><div class="toolbar"><button class="btn primary" onclick="show('pricing')">💰 Enter resale manually</button><button class="btn" onclick="openInventoryEdit({barcode:'${esc(b)}'})">＋ Add manually</button></div></div>`}finally{lookupBusy=false;$('lookupBtn').disabled=false;renderLibrary()}}
function addScannedToStock(p){openInventoryEdit({name:p.title,barcode:p.barcode,platform:p.platform||'Other',condition:'Used - Good',qty:1,cost:0,market:Math.round(p.resale||0),sell:Math.round(p.resale||0)});toast('Enter the actual purchase price before saving')}
function openInventoryEdit(item){editingId=item?.id||null;$('editTitle').textContent=editingId?'Edit Stock Item':'Add Stock Item';$('eName').value=item?.name||'';$('eBarcode').value=item?.barcode||'';$('ePlatform').value=item?.platform||'Other';$('eCondition').value=item?.condition||'Used - Good';$('eQty').value=item?.qty||1;$('eCost').value=item?.cost||0;$('eMarket').value=item?.market||0;$('eSell').value=item?.sell||0;$('editModal').classList.add('show')}
function closeEdit(){$('editModal').classList.remove('show');editingId=null}
function saveInventoryEdit(){const item={id:editingId||String(Date.now()),name:$('eName').value.trim()||'Unnamed Game',barcode:$('eBarcode').value.trim(),platform:$('ePlatform').value,condition:$('eCondition').value,qty:Math.max(1,Number($('eQty').value)||1),cost:Math.round(Number($('eCost').value)||0),market:Math.round(Number($('eMarket').value)||0),sell:Math.round(Number($('eSell').value)||0)};if(editingId)inventory=inventory.map(x=>x.id===editingId?item:x);else inventory.push(item);saveData();closeEdit();toast('Stock saved')}
function editInventory(id){const x=inventory.find(v=>v.id===id);if(x)openInventoryEdit(x)}
function deleteInventory(id){if(confirm('Delete this stock item?')){inventory=inventory.filter(x=>x.id!==id);saveData();toast('Stock deleted')}}
function clearInventory(){if(confirm('Clear all inventory?')){inventory=[];saveData();toast('Inventory cleared')}}
function clearLibrary(){if(confirm('Clear the saved library?')){library=[];saveData();toast('Library cleared')}}
function exportBackup(){const blob=new Blob([JSON.stringify({version:APP_VERSION,exportedAt:new Date().toISOString(),inventory,library},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='beau-reseller-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(Array.isArray(d.inventory))inventory=d.inventory;if(Array.isArray(d.library))library=d.library;saveData();toast('Backup restored')}catch{toast('Invalid backup file')}};r.readAsText(file)}
function compareVersions(a,b){const x=String(a||'0').replace(/^v/i,'').split('.').map(n=>parseInt(n,10)||0),y=String(b||'0').replace(/^v/i,'').split('.').map(n=>parseInt(n,10)||0);for(let i=0;i<3;i++){if((x[i]||0)!==(y[i]||0))return(x[i]||0)-(y[i]||0)}return 0}
async function checkUpdate(){const box=$('updateBox');box.innerHTML='Checking for updates…';try{const r=await fetch('./update.json?ts='+Date.now(),{cache:'no-store'}),d=await r.json(),available=String(d.version||APP_VERSION),cmp=compareVersions(available,APP_VERSION);box.innerHTML=`<b>Current app:</b> ${APP_VERSION}<br><b>Available:</b> ${esc(available)}<br><span class="muted">${esc(cmp>0?(d.message||'A newer stable release is available.'):cmp===0?'You are on the latest stable version.':'The update service reported an older release, so it has been ignored.')}</span>${cmp>0?'<div class="toolbar"><button class="btn primary" onclick="location.href=\'./ota.html?ts='+Date.now()+'\'">Install latest update</button></div>':'<div class="toolbar"><button class="btn success" disabled>✓ Up to date</button></div>'}`}catch{box.textContent='Update service unavailable. The app will continue working normally.'}}
function globalSearch(q){const s=String(q||'').trim().toLowerCase();if(!s){show('dashboard');return}const invHit=inventory.some(x=>`${x.name} ${x.barcode} ${x.platform}`.toLowerCase().includes(s));const libHit=library.some(x=>`${x.title} ${x.barcode} ${x.platform}`.toLowerCase().includes(s));if(invHit){$('invSearch').value=s;show('inventory');toast('Inventory result found')}else if(libHit){$('libSearch').value=s;show('library');toast('Library result found')}else{const digits=s.replace(/\D/g,'');show('scanner');if(digits){$('scanCode').value=digits;lookupProduct(digits)}else toast('No matching stock or library item found')}}
function init(){loadData();document.querySelectorAll('.bottom button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));$('startCam').addEventListener('click',startCamera);$('stopCam').addEventListener('click',stopCamera);$('lookupBtn').addEventListener('click',()=>lookupProduct($('scanCode').value));$('scanCode').addEventListener('keydown',e=>{if(e.key==='Enter')lookupProduct(e.target.value)});$('resale').addEventListener('input',updatePricing);$('condition').addEventListener('change',updatePricing);$('invSearch').addEventListener('input',renderInventory);$('libSearch').addEventListener('input',renderLibrary);$('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter')globalSearch(e.target.value)});$('importFile').addEventListener('change',e=>{if(e.target.files[0])importBackup(e.target.files[0])});$('checkUpdate').addEventListener('click',checkUpdate);show((location.hash||'#dashboard').slice(1));updatePricing();renderAll();checkUpdate()}
window.addEventListener('DOMContentLoaded',init);window.addEventListener('beforeunload',()=>{if(scanner)stopCamera()});