(function(){
'use strict';
const URL='https://ccdqmncjpywhpnrajfit.supabase.co';
const KEY='sb_publishable_VNuSfZizVdNhbHAPkbBPbw_YYWoqVFH';
let client=null;
function loadSdk(){return new Promise((resolve,reject)=>{if(window.supabase?.createClient)return resolve(window.supabase);const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=()=>window.supabase?.createClient?resolve(window.supabase):reject(Error('Supabase client unavailable'));s.onerror=()=>reject(Error('Could not load cloud login service'));document.head.appendChild(s)})}
async function getClient(){if(client)return client;const sdk=await loadSdk();client=sdk.createClient(URL,KEY);return client}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function inject(){if(document.getElementById('cloudAuthCard'))return;const settings=document.getElementById('settings');if(!settings)return;const card=document.createElement('div');card.className='card';card.id='cloudAuthCard';card.innerHTML=`<h2>☁️ Cloud Library & Sync</h2><div id="cloudAuthStatus" class="muted">Not signed in. Your local library still works offline.</div><div id="cloudAuthForm"><div class="row"><label>Email<input id="cloudEmail" class="input" type="email" autocomplete="email"></label><label>Password<input id="cloudPassword" class="input" type="password" autocomplete="current-password"></label></div><div class="toolbar"><button id="cloudSignIn" class="btn primary">Sign In</button><button id="cloudSignUp" class="btn">Create Account</button></div><div class="muted">Email confirmation may be required by your Supabase Auth settings.</div></div><div id="cloudSignedIn" hidden><div class="toolbar"><button id="cloudSync" class="btn success">☁️ Sync Library</button><button id="cloudSignOut" class="btn">Sign Out</button></div><div id="cloudSyncStatus" class="muted"></div></div>`;settings.querySelector('.card')?.appendChild(card);bind()}
async function refresh(){try{const c=await getClient();const {data}=await c.auth.getSession();const user=data?.session?.user;const status=document.getElementById('cloudAuthStatus'),form=document.getElementById('cloudAuthForm'),signed=document.getElementById('cloudSignedIn');if(user){status.innerHTML='Signed in as <b>'+esc(user.email||'account')+'</b>';form.hidden=true;signed.hidden=false;}else{status.textContent='Not signed in. Your local library still works offline.';form.hidden=false;signed.hidden=true;}}catch(e){const status=document.getElementById('cloudAuthStatus');if(status)status.textContent='Cloud login unavailable: '+e.message}}
async function signIn(){const email=document.getElementById('cloudEmail').value.trim(),password=document.getElementById('cloudPassword').value;if(!email||!password)return alert('Enter your email and password.');const c=await getClient();const {error}=await c.auth.signInWithPassword({email,password});if(error)return alert(error.message);await refresh();await syncInventory()}
async function signUp(){const email=document.getElementById('cloudEmail').value.trim(),password=document.getElementById('cloudPassword').value;if(!email||password.length<6)return alert('Enter an email and a password of at least 6 characters.');const c=await getClient();const {data,error}=await c.auth.signUp({email,password,options:{emailRedirectTo:location.href}});if(error)return alert(error.message);alert(data.session?'Account created and signed in.':'Account created. Check your email if confirmation is required, then return to the app.');await refresh()}
async function signOut(){const c=await getClient();await c.auth.signOut();await refresh()}
async function syncInventory(){const c=await getClient();const {data}=await c.auth.getSession();const user=data?.session?.user;if(!user){alert('Sign in first.');return}const status=document.getElementById('cloudSyncStatus');if(status)status.textContent='Syncing…';const local=Array.isArray(window.inventory)?window.inventory:[];let pushed=0,pulled=0;for(const item of local){const payload={owner_id:user.id,name:item.name||'Unnamed Game',barcode:item.barcode||null,platform:item.platform||null,condition:item.condition||null,quantity:Math.max(1,Number(item.qty)||1),cost:Number(item.cost)||0,market:Number(item.market)||0,sell:Number(item.sell)||0};try{if(item.cloudId){const {error}=await c.from('inventory').update(payload).eq('id',item.cloudId).eq('owner_id',user.id);if(!error)pushed++}else{const {data:row,error}=await c.from('inventory').insert(payload).select('id').single();if(!error&&row){item.cloudId=row.id;pushed++}}}catch{}}
try{const {data:rows,error}=await c.from('inventory').select('*').eq('owner_id',user.id).order('created_at',{ascending:true});if(!error&&Array.isArray(rows)){for(const row of rows){const found=local.some(x=>x.cloudId===row.id);if(!found){local.push({id:String(row.id),cloudId:row.id,name:row.name,barcode:row.barcode||'',platform:row.platform||'Other',condition:row.condition||'Used - Good',qty:row.quantity||1,cost:Number(row.cost)||0,market:Number(row.market)||0,sell:Number(row.sell)||0});pulled++}}window.inventory=local;localStorage.setItem('resellerInventory',JSON.stringify(local));window.renderAll?.()}}catch{}
if(status)status.textContent=`Sync complete — uploaded ${pushed}, downloaded ${pulled}.`}
function bind(){document.getElementById('cloudSignIn').onclick=signIn;document.getElementById('cloudSignUp').onclick=signUp;document.getElementById('cloudSignOut').onclick=signOut;document.getElementById('cloudSync').onclick=syncInventory;getClient().then(c=>c.auth.onAuthStateChange(()=>refresh())).catch(()=>{});refresh()}
window.CloudAuth={getClient,refresh,signIn,signUp,signOut,syncInventory};
document.addEventListener('DOMContentLoaded',inject);
})();
