(()=>{'use strict';
const $=id=>document.getElementById(id),money=v=>'$'+(Number(v)||0).toFixed(2),load=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const platforms={eBay:{fee:0.13},Facebook:{fee:0},Gumtree:{fee:0},Etsy:{fee:0.065},Other:{fee:0}};
function css(){if($('ms-css'))return;let s=document.createElement('style');s.id='ms-css';s.textContent=`#msPanel{position:fixed;inset:0;background:#f5f6f8;z-index:10001;display:none;overflow:auto}.ms-show{display:block!important}.ms-head{position:sticky;top:0;background:#fff;padding:14px;display:flex;gap:10px;align-items:center;border-bottom:1px solid #ddd}.ms-wrap{max-width:950px;margin:auto;padding:12px}.ms-card{background:#fff;border:1px solid #ddd;border-radius:14px;padding:14px;margin-bottom:12px}.ms-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.ms-stat small{display:block;color:#666}.ms-stat b{font-size:24px}.ms-row{display:flex;gap:8px;flex-wrap:wrap}.ms-row>*{flex:1;min-width:130px}.ms-input{width:100%;padding:10px;border:1px solid #bbb;border-radius:9px;font:inherit}.ms-table{width:100%;border-collapse:collapse}.ms-table th,.ms-table td{padding:9px;border-bottom:1px solid #eee;text-align:left}.ms-pill{padding:4px 8px;border-radius:20px;background:#eee;font-weight:700;font-size:12px}@media(max-width:700px){.ms-grid{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(s)}
function button(){if($('msOpen'))return;let b=document.createElement('button');b.id='msOpen';b.className='action';b.innerHTML='<strong>💵 Marketplace & Sales</strong><span>Listings, sales & net profit</span>';b.onclick=open;document.querySelector('.hero .actions')?.appendChild(b)}
function open(){css();render();$('msPanel').classList.add('ms-show');document.body.style.overflow='hidden'}function close(){ $('msPanel')?.classList.remove('ms-show');document.body.style.overflow=''}
function calc(x){let sale=+x.sale||0,cost=+x.cost||0,fee=sale*(+x.fee||0),post=+x.post||0,pack=+x.pack||0,other=+x.other||0;return {fee,net:sale-cost-fee-post-pack-other,margin:sale?(sale-cost-fee-post-pack-other)/sale*100:0}}
function render(){css();if(!$('msPanel')){let p=document.createElement('div');p.id='msPanel';p.innerHTML=`<div class="ms-head"><button class="btn" id="msClose">← Back</button><h2>💵 Marketplace & Sales</h2></div><div class="ms-wrap"><div class="ms-card"><h3>📊 Sales Dashboard</h3><div class="ms-grid" id="msStats"></div></div><div class="ms-card"><h3>➕ Record Sale</h3><div class="ms-row"><label>Item<input id="msItem" class="ms-input" placeholder="Game/item"></label><label>Sale price<input id="msSale" class="ms-input" type="number"></label><label>Purchase cost<input id="msCost" class="ms-input" type="number"></label><label>Platform<select id="msPlatform" class="ms-input">${Object.keys(platforms).map(p=>`<option>${p}</option>`).join('')}</select></label></div><div class="ms-row"><label>Postage<input id="msPost" class="ms-input" type="number" value="0"></label><label>Packaging<input id="msPack" class="ms-input" type="number" value="0"></label><label>Other costs<input id="msOther" class="ms-input" type="number" value="0"></label></div><button class="btn primary" id="msAdd">💰 Record sale</button><div id="msPreview"></div></div><div class="ms-card"><h3>🏷️ Listing Performance</h3><div id="msPerf"></div></div><div class="ms-card"><h3>📋 Sales History</h3><button class="btn" id="msCsv">Export CSV</button><div id="msHistory"></div></div></div>`;document.body.appendChild(p);$('msClose').onclick=close;$('msAdd').onclick=addSale;$('msCsv').onclick=csv;['msSale','msCost','msPost','msPack','msOther','msPlatform'].forEach(id=>$(id).oninput=preview)}preview()}
function sales(){return load('resellerSales',[])}
function preview(){if(!$('msPreview'))return;let platform=$('msPlatform').value,s={sale:+$('msSale').value||0,cost:+$('msCost').value||0,fee:platforms[platform].fee,post:+$('msPost').value||0,pack:+$('msPack').value||0,other:+$('msOther').value||0},r=calc(s);$('msPreview').innerHTML=`<p>Platform fee: <b>${money(r.fee)}</b> · Net profit: <b>${money(r.net)}</b> · Margin: <b>${r.margin.toFixed(1)}%</b></p>`}
function addSale(){let platform=$('msPlatform').value,s={id:Date.now(),item:$('msItem').value.trim()||'Unnamed item',sale:+$('msSale').value||0,cost:+$('msCost').value||0,fee:platforms[platform].fee,platform,post:+$('msPost').value||0,pack:+$('msPack').value||0,other:+$('msOther').value||0,date:new Date().toISOString()};if(!s.sale){alert('Enter a sale price.');return}let a=sales();a.unshift(s);save('resellerSales',a);render();alert('Sale recorded.')}
function renderStats(){let a=sales(),rev=a.reduce((s,x)=>s+x.sale,0),net=a.reduce((s,x)=>s+calc(x).net,0),fees=a.reduce((s,x)=>s+calc(x).fee,0),cost=a.reduce((s,x)=>s+x.cost,0);$('msStats').innerHTML=[['REVENUE',money(rev)],['COST OF STOCK',money(cost)],['FEES',money(fees)],['NET PROFIT',money(net)]].map(x=>`<div class="ms-stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
function renderPerf(){let a=sales(),by={};a.forEach(x=>(by[x.platform]??=[]).push(x));$('msPerf').innerHTML=Object.entries(by).map(([p,v])=>{let rev=v.reduce((s,x)=>s+x.sale,0),net=v.reduce((s,x)=>s+calc(x).net,0);return`<div class="ms-row" style="padding:8px 0;border-bottom:1px solid #eee"><b>${p}</b><span>${v.length} sales</span><span>${money(rev)} revenue</span><span>${money(net)} net</span></div>`}).join('')||'<p>No sales recorded yet.</p>'}
function renderHistory(){let a=sales();$('msHistory').innerHTML=a.map((x,i)=>{let r=calc(x);return`<div class="ms-row" style="padding:9px 0;border-bottom:1px solid #eee"><span><b>${x.item}</b><br><small>${x.platform} · ${new Date(x.date).toLocaleDateString()}</small></span><span>${money(x.sale)}</span><span>Net ${money(r.net)}</span><button class="btn" onclick="window.msDel(${i})">×</button></div>`}).join('')||'<p>No sales recorded yet.</p>'}
window.msDel=i=>{let a=sales();a.splice(i,1);save('resellerSales',a);render()};
function csv(){let a=sales(),rows=[['Item','Platform','Sale','Cost','Fee','Postage','Packaging','Other','Net Profit','Margin','Date']];a.forEach(x=>{let r=calc(x);rows.push([x.item,x.platform,x.sale,x.cost,r.fee,x.post,x.pack,x.other,r.net,r.margin,new Date(x.date).toISOString()])});let blob=new Blob([rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n')],{type:'text/csv'}),u=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=u;ael.download='reseller-sales.csv';ael.click();URL.revokeObjectURL(u)}
function init(){css();button();new MutationObserver(button).observe(document.body,{childList:true,subtree:true})}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();