/* Beau's Game Inventory — pricing engine v3.2.0 */
(function(){
'use strict';
const WORKER='https://beau-reseller-pricing.beaustwrt248.workers.dev';
const nativeFetch=window.fetch.bind(window);
const nums=v=>{if(Array.isArray(v))return v.flatMap(nums);if(typeof v==='number'&&Number.isFinite(v)&&v>0)return[v];if(typeof v==='string'){const n=Number(v.replace(/[^0-9.]/g,''));return Number.isFinite(n)&&n>0?[n]:[]}return[]};
const first=(o,keys)=>{for(const k of keys){const n=nums(o?.[k])[0];if(n)return n}return 0};
const median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};
const robust=a=>{const v=a.filter(x=>x>0);if(!v.length)return 0;if(v.length<3)return median(v);const m=median(v),d=v.map(x=>Math.abs(x-m)),mad=median(d);if(!mad)return m;const k=v.filter(x=>Math.abs(x-m)<=3*mad);return median(k.length?k:v)};
const unwrap=d=>d?.data?.data?.data||d?.data?.data||d?.data||d;
const titleOf=p=>String(p?.title||p?.name||p?.product_name||p?.productName||'').trim();
function usefulProduct(p){const t=titleOf(p).toLowerCase();if(t.length<3)return false;if(['game','product','item','unknown game','unknown product','unknown','generic product'].includes(t))return false;if(/^([a-z0-9_-]{20,}):(\d+)$/.test(t))return false;return true}
function collectObjects(v,seen=new Set(),out=[]){if(!v||typeof v!=='object'||seen.has(v))return out;seen.add(v);if(Array.isArray(v)){for(const x of v)collectObjects(x,seen,out);return out}out.push(v);for(const k of Object.keys(v))if(k!=='image'&&k!=='images')collectObjects(v[k],seen,out);return out}
function findProduct(d){const objs=collectObjects(d);return objs.find(usefulProduct)||objs.find(o=>titleOf(o).length>=3)||null}
function buyGuide(resale,condition='Used - Good'){const r=Number(resale)||0;const rates={'New':.30,'Like New':.28,'Used - Good':.25,'Used - Fair':.23,'For Parts':.21};const recommended=rates[condition]??.25;return{conservative:Math.round(r*.21),recommended:Math.round(r*recommended),maximum:Math.round(r*.30),recommendedRate:recommended,condition};}
function normalise(data,barcode){const root=unwrap(data)||{};const p=findProduct(data);const pricing=root.pricing||data?.pricing||p?.pricing||{};const stores=[...(Array.isArray(root.stores)?root.stores:[]),...(Array.isArray(data?.stores)?data.stores:[])];const all=[p,root,data,pricing,...stores].filter(Boolean);const retailKeys=['retailPrice','newPrice','brandNewPrice','retail_price','rrp','current_price','new_price','priceNew','new'];const secondKeys=['secondHandPrice','usedPrice','marketPrice','market_price','used_price','second_hand_price','secondHand','used','priceUsed','preownedPrice','preOwnedPrice','secondHandValue','resalePrice','suggestedResale','recommendedResale'];const collect=keys=>all.flatMap(o=>keys.flatMap(k=>nums(o?.[k])));const rv=collect(retailKeys),sv=collect(secondKeys),retail=robust(rv),second=robust(sv),secondEstimated=!second&&!!retail;const resale=first(pricing,['suggestedResale','resalePrice','recommendedResale'])||second||(retail?retail*.75:0),guide=buyGuide(resale,'Used - Good');const title=titleOf(p)||titleOf(root)||'Unknown game';const image=p?.image||p?.image_url||p?.imageUrl||p?.thumbnail||p?.thumbnail_url||(Array.isArray(p?.images)?p.images[0]:'')||'';const platform=p?.platform||p?.console||p?.system||p?.consoleName||root?.platform||'';const sourceNames=[...new Set(stores.map(s=>s?.source||s?.store||s?.storeName||s?.retailer||s?.name).filter(Boolean).map(String))];if(!sourceNames.length&&p?.source)sourceNames.push(String(p.source));const count=Math.max(new Set(rv).size,new Set(sv).size,sourceNames.length);return{title,image,platform,retail,second,resale,buy:guide.recommended,buyGuide:guide,barcode,sources:stores,sourceNames,confidence:count>=4?'High':count>=2?'Medium':'Low',sampleCount:count,secondEstimated};}
async function json(url,init){const r=await nativeFetch(url,{...init,cache:'no-store',headers:{Accept:'application/json',...(init?.headers||{})}}),t=await r.text();let d;try{d=JSON.parse(t)}catch(_){throw Error('Invalid JSON (HTTP '+r.status+')')}if(!r.ok||d?.success===false)throw Error(d?.error||d?.message||('HTTP '+r.status));return d}
function barcodeVariants(code){const c=String(code||'').replace(/\D/g,'');const a=[c];if(c.length===13&&c.startsWith('0'))a.push(c.slice(1));return[...new Set(a)].filter(Boolean)}
async function workerLookup(code){let last;for(const b of barcodeVariants(code)){for(const path of ['/lookup','/api/lookup','/price','']){try{return{data:await json(WORKER+path+'?barcode='+encodeURIComponent(b)),route:path||'worker',barcode:b}}catch(e){last=e}}try{return{data:await json(WORKER,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({barcode:b})}),route:'worker-post',barcode:b}}catch(e){last=e}}throw last||Error('Pricing service unavailable')}
const localCatalog={'5030917298462':{product:{title:'Diablo IV',platform:'PlayStation 5',brand:'Blizzard Entertainment'},pricing:{retailPrice:88},stores:[{source:'Australian retail reference',retailPrice:88}]}};
async function lookup(code){const b=String(code||'').replace(/\D/g,'');if(!b)throw Error('Enter a barcode');try{const w=await workerLookup(b);const product=findProduct(w.data);if(product&&titleOf(product))return w;const local=localCatalog[b];if(local)return{data:local,route:'Australian barcode catalog',barcode:b};throw Error('No usable product title was returned for this barcode.')}catch(e){const local=localCatalog[b];if(local)return{data:local,route:'Australian barcode catalog',barcode:b};throw e}}
window.BeauPricingEngine={normalise,lookup,buyGuide,version:'3.2.0'};
})();
