/* Beau's Game Inventory — pricing engine v2.8.0 */
(function(){
'use strict';
const WORKER='https://beau-reseller-pricing.beaustwrt248.workers.dev';
const nativeFetch=window.fetch.bind(window);
const nums=v=>{if(Array.isArray(v))return v.flatMap(nums);if(typeof v==='number'&&Number.isFinite(v)&&v>0)return[v];if(typeof v==='string'){const n=Number(v.replace(/[^0-9.]/g,''));return Number.isFinite(n)&&n>0?[n]:[]}return[]};
const first=(o,keys)=>{for(const k of keys){const n=nums(o?.[k])[0];if(n)return n}return 0};
const median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};
const robust=a=>{const v=a.filter(x=>x>0);if(!v.length)return 0;if(v.length<3)return median(v);const m=median(v),d=v.map(x=>Math.abs(x-m)),mad=median(d);if(!mad)return m;const k=v.filter(x=>Math.abs(x-m)<=3*mad);return median(k.length?k:v)};
const unwrap=d=>d?.data?.data?.data||d?.data?.data||d?.data||d;
function findProduct(d){const r=unwrap(d)||{};const a=[r.product,r.item,r.result?.product,r.result?.item,r.products?.[0],r.items?.[0],r.results?.[0],d?.product,d?.item,d?.products?.[0],d?.items?.[0],d?.result?.product,d?.data?.product,d?.data?.item,d?.data?.products?.[0],d?.data?.items?.[0]];return a.find(x=>x&&typeof x==='object'&&!Array.isArray(x))||null}
function usefulProduct(p){if(!p)return false;const t=String(p.title||p.name||p.product_name||p.productName||'').trim().toLowerCase();if(t.length<3)return false;if(['game','product','item','unknown game','unknown product','unknown'].includes(t))return false;if(/^([a-z0-9_-]{20,}):(\d+)$/.test(t))return false;return true}
function normalise(data,barcode){const root=unwrap(data)||{};const p=findProduct(data);const pricing=root.pricing||data?.pricing||p?.pricing||{};const stores=[...(Array.isArray(root.stores)?root.stores:[]),...(Array.isArray(data?.stores)?data.stores:[])];const all=[p,root,data,pricing,...stores].filter(Boolean);const retailKeys=['retailPrice','newPrice','brandNewPrice','retail_price','rrp','current_price','new_price','priceNew','new','price'];const secondKeys=['secondHandPrice','usedPrice','marketPrice','market_price','used_price','second_hand_price','secondHand','used','priceUsed','preownedPrice','preOwnedPrice','secondHandValue','resalePrice'];const collect=keys=>all.flatMap(o=>keys.flatMap(k=>nums(o?.[k])));const rv=collect(retailKeys),sv=collect(secondKeys),retail=robust(rv),second=robust(sv),secondEstimated=!second&&!!retail;const resale=first(pricing,['suggestedResale','resalePrice','recommendedResale'])||second||(retail?retail*.75:0),buy=first(pricing,['maximumBuy','suggestedBuy','recommendedBuy'])||(resale?resale*.70:0);const title=p?.title||p?.name||p?.product_name||p?.productName||root?.title||root?.name||'Unknown game';const image=p?.image||p?.image_url||p?.imageUrl||p?.thumbnail||p?.thumbnail_url||(Array.isArray(p?.images)?p.images[0]:'')||'';const platform=p?.platform||p?.console||p?.system||p?.consoleName||root?.platform||'';const sourceNames=[...new Set(stores.map(s=>s?.source||s?.store||s?.storeName||s?.retailer||s?.name).filter(Boolean).map(String))];if(!sourceNames.length&&p?.source)sourceNames.push(String(p.source));const count=Math.max(new Set(rv).size,new Set(sv).size,sourceNames.length);return{title,image,platform,retail,second,resale,buy,barcode,sources:stores,sourceNames,confidence:count>=4?'High':count>=2?'Medium':'Low',sampleCount:count,secondEstimated}}
async function json(url,init){const r=await nativeFetch(url,{...init,cache:'no-store',headers:{Accept:'application/json',...(init?.headers||{})}}),t=await r.text();let d;try{d=JSON.parse(t)}catch(_){throw Error('Invalid JSON (HTTP '+r.status+')')}if(!r.ok||d?.success===false)throw Error(d?.error||d?.message||('HTTP '+r.status));return d}
function barcodeVariants(code){const c=String(code||'').replace(/\D/g,'');const a=[c];if(c.length===13&&c.startsWith('0'))a.push(c.slice(1));return[...new Set(a)].filter(Boolean)}
async function workerLookup(code){let last;for(const b of barcodeVariants(code)){for(const path of ['/lookup','/api/lookup','/price','']){try{return{data:await json(WORKER+path+'?barcode='+encodeURIComponent(b)),route:path||'worker',barcode:b}}catch(e){last=e}}try{return{data:await json(WORKER,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({barcode:b})}),route:'worker-post',barcode:b}}catch(e){last=e}}throw last||Error('Pricing service unavailable')}
/* Verified Australian game barcode fallbacks. These are used only when the worker returns a generic product. */
const localCatalog={
 '5030917298462':{product:{title:'Diablo IV',platform:'PlayStation 5',brand:'Blizzard Entertainment'},pricing:{retailPrice:88},stores:[{source:'Australian retail reference',retailPrice:88}]}
};
async function lookup(code){const b=String(code||'').replace(/\D/g,'');if(!b)throw Error('Enter a barcode');try{const w=await workerLookup(b);if(usefulProduct(findProduct(w.data)))return w;const local=localCatalog[b];if(local)return{data:local,route:'Australian barcode catalog',barcode:b};throw Error('The pricing service returned a generic product and no local match is available.')}catch(e){const local=localCatalog[b];if(local)return{data:local,route:'Australian barcode catalog',barcode:b};throw e}}
window.fetch=window.fetch||nativeFetch;
window.BeauPricingEngine={normalise,lookup,version:'2.8.0'};
})();
