/* Beau's Game Inventory v1.7.0 — reseller workflow tools */
(function(){'use strict';
const INV='resellerInventory';
const money=v=>'$'+Number(v||0).toFixed(2);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const get=()=>{try{return JSON.parse(localStorage.getItem(INV)||'[]')}catch(e){return[]}};
const save=x=>localStorage.setItem(INV,JSON.stringify(x));
function page(id){return document.getElementById('page-'+id)}
function style(){if(document.getElementById('proStyle'))return;const s=document.createElement('style');s.id='proStyle';s.textContent='.pro-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.pro-card{padding:14px;border:1px solid #e5e7eb;border-radius:12px;background:#fff;margin-top:10px}.pro-card h3{margin:0 0 8px}.pro-age{font-size:12px;color:#6b7280}.pro-low{border-left:5px solid #dc2626}.pro-good{border-left:5px solid #16a34a}@media(max-width:700px){.pro-grid{grid-template-columns:1fr}}body.dark-mode .pro-card{background:#1f2937;border-color:#374151;color:#f9fafb}';document.head.appendChild(s)}
function stockHealth(){const p=page('dashboard');if(!p||document.getElementById('proStockHealth'))return;const b=document.createElement('section');b.className='panel';b.id='proStockHealth';b.innerHTML='<h2>📦 Stock Health</h2><div id="proStockHealthBody"></div>';p.appendChild(b);renderHealth()}
function renderHealth(){const box=document.getElementById('proStockHealthBody');if(!box)return;const items=get();const now=Date.now();let low=items.filter(i=>Number(i.quantity||0)<=1),aged=items.filter(i=>i.dateAdded&&(now-new Date(i.dateAdded).getTime())>=30*86400000);box.innerHTML=`<div class="pro-grid"><div class="pro-card ${low.length?'pro-low':'pro-good'}"><h3>Low Stock</h3><strong>${low.length}</strong><p>Items with 1 unit or less.</p></div><div class="pro-card ${aged.length?'pro-low':'pro-good'}"><h3>30+ Day Stock</h3><strong>${aged.length}</strong><p>Items held for 30 days or more.</p></div></div>`+(aged.length?'<div class="pro-card"><h3>Oldest Stock</h3>'+aged.sort((a,b)=>new Date(a.dateAdded)-new Date(b.dateAdded)).slice(0,8).map(i=>`<p><strong>${esc(i.name)}</strong> <span class="pro-age">${Math.floor((now-new Date(i.dateAdded).getTime())/86400000)} days</span></p>`).join('')+'</div>':'')}
function sellButtons(){const p=page('inventory');if(!p||document.getElementById('proSellTools'))return;const b=document.createElement('section');b.className='panel';b.id='proSellTools';b.innerHTML='<h2>🧾 Quick Sale</h2><p>Select an item, enter the sale details and stock will be reduced automatically.</p><select id="proSaleItem"><option value="">Choose inventory item…</option></select><div class="pro-grid"><label>Quantity<input id="proSaleQty" type="number" min="1" value="1"></label><label>Sale price ($)<input id="proSalePrice" type="number" min="0" step="0.01"></label><label>Fees ($)<input id="proSaleFees" type="number" min="0" step="0.01" value="0"></label><label>Postage ($)<input id="proSalePostage" type="number" min="0" step="0.01" value="0"></label></div><div id="proSaleResult" class="pro-card">Choose an item to record a sale.</div><div class="actions"><button class="success" id="proRecordSale">🧾 Record Sale</button></div>';p.insertBefore(b,p.firstChild);fillSaleItems();document.getElementById('proSaleItem').onchange=salePreview;document.getElementById('proSaleQty').oninput=salePreview;document.getElementById('proSalePrice').oninput=salePreview;document.getElementById('proSaleFees').oninput=salePreview;document.getElementById('proSalePostage').oninput=salePreview;document.getElementById('proRecordSale').onclick=recordSale}
function fillSaleItems(){const s=document.getElementById('proSaleItem');if(!s)return;const old=s.value;s.innerHTML='<option value="">Choose inventory item…</option>'+get().filter(i=>Number(i.quantity||0)>0).map(i=>`<option value="${esc(i.id)}">${esc(i.name)} — ${Number(i.quantity||0)} in stock</option>`).join('');s.value=old}
function salePreview(){const id=document.getElementById('proSaleItem')?.value,i=get().find(x=>String(x.id)===String(id)),r=document.getElementById('proSaleResult');if(!i||!r){if(r)r.textContent='Choose an item to record a sale.';return}const q=Math.min(Number(document.getElementById('proSaleQty').value||1),Number(i.quantity||0)),price=Number(document.getElementById('proSalePrice').value||i.selling||i.marketPrice||0),fees=Number(document.getElementById('proSaleFees').value||0),post=Number(document.getElementById('proSalePostage').value||0),profit=price*q-fees-post-Number(i.cost||0)*q;r.innerHTML=`<strong>${esc(i.name)}</strong><p>Net profit: <strong>${money(profit)}</strong> • Remaining stock: ${Math.max(0,Number(i.quantity||0)-q)}</p>`}
function recordSale(){const id=document.getElementById('proSaleItem')?.value,i=get().find(x=>String(x.id)===String(id));if(!i)return alert('Choose an inventory item.');const q=Math.max(1,Number(document.getElementById('proSaleQty').value||1));if(q>Number(i.quantity||0))return alert('You do not have enough stock.');const revenue=Number(document.getElementById('proSalePrice').value||i.selling||i.marketPrice||0)*q,fees=Number(document.getElementById('proSaleFees').value||0),postage=Number(document.getElementById('proSalePostage').value||0);if(revenue<=0)return alert('Enter a sale price.');i.quantity-=q;i.sales=Array.isArray(i.sales)?i.sales:[];i.sales.push({date:new Date().toISOString(),quantity:q,revenue,fees,postage,cost:Number(i.cost||0)*q});save(get());fillSaleItems();salePreview();document.getElementById('proSaleQty').value='1';document.getElementById('proSalePrice').value='';document.getElementById('proSaleFees').value='0';document.getElementById('proSalePostage').value='0';if(typeof window.displayItems==='function')window.displayItems();if(typeof window.updateDashboard==='function')window.updateDashboard();alert('Sale recorded and stock updated.')}
function reports(){const p=page('sales');if(!p||document.getElementById('proReportCards'))return;const b=document.createElement('section');b.className='panel';b.id='proReportCards';b.innerHTML='<h2>📈 Business Snapshot</h2><div id="proReportBody"></div>';p.appendChild(b);renderReports()}
function renderReports(){const box=document.getElementById('proReportBody');if(!box)return;let revenue=0,fees=0,post=0,cost=0,units=0;get().forEach(i=>(i.sales||[]).forEach(s=>{units+=Number(s.quantity||1);revenue+=Number(s.revenue||0);fees+=Number(s.fees||0);post+=Number(s.postage||0);cost+=Number(s.cost||0)}));const profit=revenue-fees-post-cost;box.innerHTML=`<div class="pro-grid"><div class="pro-card"><h3>Units Sold</h3><strong>${units}</strong></div><div class="pro-card"><h3>Revenue</h3><strong>${money(revenue)}</strong></div><div class="pro-card"><h3>Net Profit</h3><strong>${money(profit)}</strong></div><div class="pro-card"><h3>Profit Margin</h3><strong>${revenue?(profit/revenue*100).toFixed(1):'0.0'}%</strong></div></div>`}
function init(){style();setTimeout(()=>{stockHealth();sellButtons();reports();renderHealth();renderReports()},300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.addEventListener('beau:update-ready',init);window.addEventListener('hashchange',()=>setTimeout(init,100));
})();
