(function(){
'use strict';
const K='resellerSuiteV1';
const $=id=>document.getElementById(id);
const money=n=>'$'+(Number(n)||0).toFixed(2);
function load(){try{return JSON.parse(localStorage.getItem(K))||{sales:[],listings:[],deals:[]}}catch(e){return{sales:[],listings:[],deals:[]}}}
function save(d){localStorage.setItem(K,JSON.stringify(d));}
function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
function stock(){try{return JSON.parse(localStorage.getItem('resellerInventory')||'[]')}catch(e){return[]}}
function inject(){
 if($('resellerSuite'))return;
 const s=document.createElement('section');s.id='resellerSuite';s.className='section';s.innerHTML=`<div class="card"><h2>🚀 Reseller Command Centre</h2><div class="muted">Buying, selling, listings and profit intelligence in one place.</div><div class="stats" id="suiteStats"></div></div>
 <div class="grid2"><div class="card"><h2>🧠 Smart Buying</h2><div class="row"><label>Market value<input id="siMarket" class="input" type="number" min="0"></label><label>Seller asks<input id="siAsk" class="input" type="number" min="0"></label><label>Fees %<input id="siFee" class="input" type="number" value="13" min="0"></label><label>Postage<input id="siPost" class="input" type="number" value="0" min="0"></label></div><button class="btn primary" id="siCheck">🧠 Analyse Deal</button><div id="siDeal" class="result"></div></div>
 <div class="card"><h2>📋 Listing Assistant</h2><div class="row"><label>Item<input id="liName" class="input" placeholder="PS5 game"></label><label>Platform<input id="liPlatform" class="input" placeholder="PlayStation 5"></label><label>Condition<select id="liCondition"><option>Used - Good</option><option>Like New</option><option>New</option><option>Used - Fair</option></select></label><label>Price<input id="liPrice" class="input" type="number" min="0"></label></div><button class="btn primary" id="liGenerate">✨ Generate Listing</button><textarea id="liOutput" class="input" rows="7" style="margin-top:10px;width:100%" placeholder="Your listing will appear here..."></textarea><button class="btn" id="liCopy">📋 Copy Listing</button></div></div>
 <div class="card"><h2>💵 Record Sale</h2><div class="row"><label>Item<input id="saleName" class="input"></label><label>Sale price<input id="salePrice" class="input" type="number" min="0"></label><label>Cost<input id="saleCost" class="input" type="number" min="0"></label><label>Fees<input id="saleFees" class="input" type="number" min="0"></label><label>Postage<input id="salePost" class="input" type="number" min="0"></label><label>Other costs<input id="saleOther" class="input" type="number" min="0"></label></div><button class="btn primary" id="saleSave">💰 Record Sale</button></div>
 <div class="card"><h2>📊 Performance</h2><div id="suiteReport"></div><div class="toolbar"><button class="btn" id="suiteCsv">📤 Export Sales CSV</button><button class="btn" id="suiteRefresh">🔄 Refresh</button></div></div>`;
 const settings=$('settings');settings.parentNode.insertBefore(s,settings); 
 const drawer=document.querySelector('.drawer-panel'); if(drawer){const b=document.createElement('button');b.className='drawer-item';b.innerHTML='<span>🚀 Reseller Command Centre</span><span>›</span>';b.onclick=()=>{closeMenu();window.show('resellerSuite')};drawer.insertBefore(b,drawer.querySelector('hr'));}
}
function analyse(){const m=+($('siMarket').value||0),a=+($('siAsk').value||0),f=+($('siFee').value||0),p=+($('siPost').value||0);const net=m*(1-f/100)-p-a;const max=m*(1-f/100)-p- Math.max(0,m*.3);const score=m>0?Math.max(0,Math.min(100,Math.round((net/Math.max(m,1))*250+50))):0;const label=score>=85?'🔥 EXCELLENT':score>=70?'🟢 GOOD':score>=50?'🟡 CAUTION':'🔴 PASS';$('siDeal').innerHTML=`<div class="list-item"><span>Deal score</span><b>${score}/100 ${label}</b></div><div class="list-item"><span>Recommended offer</span><b>${money(Math.max(0,m*(1-f/100)-p-m*.25))}</b></div><div class="list-item"><span>Maximum offer</span><b>${money(Math.max(0,max))}</b></div><div class="list-item"><span>Expected net profit at asking</span><b>${money(net)}</b></div>`}
function listing(){const n=$('liName').value||'Item',p=$('liPlatform').value||'',c=$('liCondition').value||'Used - Good',v=+($('liPrice').value||0);const text=`${n} – ${p}\nCondition: ${c}\n\nGenuine item in the condition shown. Please review the photos for exact condition and included accessories.\n\nPrice: ${money(v)}\n\nFast dispatch and secure packaging.`;$('liOutput').value=text;const d=load();d.listings.push({date:new Date().toISOString(),name:n,platform:p,condition:c,price:v});save(d)}
function sale(){const d=load(),sp=+($('salePrice').value||0),c=+($('saleCost').value||0),f=+($('saleFees').value||0),p=+($('salePost').value||0),o=+($('saleOther').value||0);d.sales.push({date:new Date().toISOString(),name:$('saleName').value||'Sale',sale:sp,cost:c,fees:f,postage:p,other:o,net:sp-c-f-p-o});save(d);render();['saleName','salePrice','saleCost','saleFees','salePost','saleOther'].forEach(id=>$(id).value='')}
function render(){const d=load(),sales=d.sales,total=sales.reduce((a,x)=>a+(+x.sale||0),0),profit=sales.reduce((a,x)=>a+(+x.net||0),0),cost=sales.reduce((a,x)=>a+(+x.cost||0),0),margin=total?profit/total*100:0;const inv=stock();const invCost=inv.reduce((a,x)=>a+(+x.cost||0)*(+x.quantity||1),0);$('suiteStats').innerHTML=`<div class="stat"><span>SALES</span><strong>${money(total)}</strong></div><div class="stat"><span>NET PROFIT</span><strong>${money(profit)}</strong></div><div class="stat"><span>MARGIN</span><strong>${margin.toFixed(1)}%</strong></div><div class="stat"><span>STOCK COST</span><strong>${money(invCost)}</strong></div>`;const recent=sales.slice(-10).reverse();$('suiteReport').innerHTML=recent.length?recent.map(x=>`<div class="list-item"><span>${esc(x.name)} · ${new Date(x.date).toLocaleDateString()}</span><b>${money(x.net)}</b></div>`).join(''):'<div class="muted">No sales recorded yet.</div>'}
function csv(){const d=load(),rows=[['Date','Item','Sale Price','Cost','Fees','Postage','Other','Net Profit'],...d.sales.map(x=>[x.date,x.name,x.sale,x.cost,x.fees,x.postage,x.other,x.net])];const blob=new Blob([rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='reseller-sales.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function init(){inject();$('siCheck').onclick=analyse;$('liGenerate').onclick=listing;$('liCopy').onclick=()=>navigator.clipboard?.writeText($('liOutput').value);$('saleSave').onclick=sale;$('suiteCsv').onclick=csv;$('suiteRefresh').onclick=render;render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();