/* Beau's Reseller Hub — Smart Buy + Stock Intelligence v1.4 */
(function(){'use strict';
function whole(v){return Math.round(Number(v)||0)}
function evaluate(resale,asking){const r=Number(resale)||0,a=Number(asking);const b10=whole(r*.10),b20=whole(r*.20),b25=whole(r*.25),b30=whole(r*.30),b40=whole(r*.40);if(!Number.isFinite(a)||a<0)return{status:'ENTER PRICE',className:'neutral',message:'Enter the seller’s asking price.',b10,b20,b25,b30,b40};if(a<=b25)return{status:'BUY',className:'buy',message:'Strong buy — at or below your recommended 25% target.',b10,b20,b25,b30,b40};if(a<=b30)return{status:'NEGOTIATE',className:'negotiate',message:'Potential buy — negotiate toward your 25% target.',b10,b20,b25,b30,b40};if(a<=b40)return{status:'CAUTION',className:'caution',message:'Possible buy — above 30%, but still within your 40% maximum.',b10,b20,b25,b30,b40};return{status:'PASS',className:'pass',message:'Above your 40% maximum — pass unless there is a special reason.',b10,b20,b25,b30,b40}}
function render(){const resale=document.getElementById('resale'),asking=document.getElementById('askingPrice'),out=document.getElementById('smartResult');if(!resale||!asking||!out)return;const r=Number(resale.value)||0,a=Number(asking.value);if(!r||!Number.isFinite(a)||a<0){out.innerHTML='<div class="muted">Enter an expected resale value and seller asking price.</div>';return}const d=evaluate(r,a),profit=whole(r-a);out.innerHTML=`<div class="list-item"><span>Decision</span><b>${d.status}</b></div><div class="list-item"><span>Seller asking</span><b>$${whole(a)}</b></div><div class="list-item"><span>10% minimum target</span><b>$${d.b10}</b></div><div class="list-item"><span>20% target</span><b>$${d.b20}</b></div><div class="list-item"><span>25% recommended</span><b>$${d.b25}</b></div><div class="list-item"><span>30% target</span><b>$${d.b30}</b></div><div class="list-item"><span>40% maximum</span><b>$${d.b40}</b></div><div class="list-item"><span>Potential gross profit</span><b>$${profit}</b></div><p class="muted">${d.message}</p>`}
function readInventory(){try{const x=JSON.parse(localStorage.getItem('resellerInventory')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function pct(x){const market=Number(x.market||x.sell||0),cost=Number(x.cost||0);return market>0?Math.round(cost/market*100):null}
function deal(p){if(p===null)return'NO MARKET PRICE';if(p<=25)return'GREAT DEAL';if(p<=30)return'GOOD DEAL';if(p<=40)return'CAUTION';return'OVER 40%'}
function alerts(x,p){const a=[];if(!x.barcode)a.push('Missing barcode');if(p===null)a.push('Missing market price');if(Number(x.cost||0)===0)a.push('Purchase cost not entered');if(p!==null&&p>40)a.push('Above 40% buy limit');if(Number(x.sell||x.market||0)>0&&Number(x.cost||0)>0&&Number(x.sell||x.market)-Number(x.cost)<=0)a.push('No projected profit');return a}
function intelligence(){const inv=readInventory(),rows=inv.map(x=>{const q=Math.max(1,Number(x.qty)||1),cost=Number(x.cost)||0,market=Number(x.market||x.sell)||0,p=pct(x),issues=alerts(x,p);return{item:x,name:x.name||'Unnamed Game',cost:cost*q,sales:market*q,p,issues}}),capital=rows.reduce((s,x)=>s+x.cost,0),sales=rows.reduce((s,x)=>s+x.sales,0),profit=sales-capital,over=rows.filter(x=>x.p!==null&&x.p>40).length,great=rows.filter(x=>x.p!==null&&x.p<=25).length,noPrice=rows.filter(x=>x.p===null).length,attention=rows.filter(x=>x.issues.length).slice(0,6),best=rows.filter(x=>x.p!==null).sort((a,b)=>a.p-b.p).slice(0,5);let card=document.getElementById('stockIntelCard');const dash=document.getElementById('dashboard');if(!dash)return;if(!card){card=document.createElement('div');card.id='stockIntelCard';card.className='card';dash.appendChild(card)}card.innerHTML=`<h2>📊 Stock Intelligence</h2><div class="stats"><div class="stat"><span>CAPITAL</span><strong>$${whole(capital)}</strong></div><div class="stat"><span>POTENTIAL PROFIT</span><strong>$${whole(profit)}</strong></div><div class="stat"><span>GREAT DEALS</span><strong>${great}</strong></div><div class="stat"><span>NEEDS ATTENTION</span><strong>${attention.length}</strong></div></div><div class="result"><div class="list-item"><span>Games without market pricing</span><b>${noPrice}</b></div><div class="list-item"><span>Stock above 40% buy limit</span><b>${over}</b></div><div class="list-item"><span>Potential sales value</span><b>$${whole(sales)}</b></div></div><h3>🚨 Needs attention</h3>${attention.length?attention.map(x=>`<div class="list-item"><div><b>${esc(x.name)}</b><div class="muted">${esc(x.issues.join(' · '))}</div></div><b>${x.p===null?'—':x.p+'%'}</b></div>`).join(''):'<div class="empty">Everything looks healthy. 🎉</div>'}<h3>🏆 Best buys in stock</h3>${best.length?best.map(x=>`<div class="list-item"><div><b>${esc(x.name)}</b><div class="muted">${x.p}% of market · ${deal(x.p)}</div></div><b>$${whole(x.cost)}</b></div>`).join(''):'<div class="empty">Add stock to see your best buys.</div>'}`}
window.BeauSmartBuy={evaluate,render,version:'1.4.0',buyRange:{min:10,max:40}};
window.BeauStockIntelligence={render:intelligence,version:'1.1.0'};
window.addEventListener('DOMContentLoaded',()=>{const b=document.getElementById('smartBuyBtn');if(b)b.addEventListener('click',render);const r=document.getElementById('resale'),a=document.getElementById('askingPrice');if(r)r.addEventListener('input',render);if(a)a.addEventListener('input',render);intelligence();document.querySelectorAll('.bottom button').forEach(b=>b.addEventListener('click',()=>setTimeout(intelligence,0)));window.addEventListener('storage',intelligence)});
})();
