/* v1.8.0 Smart Scan workflow. Uses a configurable product lookup endpoint; never invents prices. */
(function(){'use strict';
const ENDPOINT='https://www.barcodelookup.com/api';
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function inv(){try{return JSON.parse(localStorage.getItem('resellerInventory')||'[]')}catch(e){return[]}}
function money(n){return '$'+Number(n||0).toFixed(2)}
function getBuyPct(){try{return Number(JSON.parse(localStorage.getItem('beauAdminSettings')||'{}').buyPct)||70}catch(e){return 70}}
async function lookup(barcode){const r=await fetch(ENDPOINT+'?barcode='+encodeURIComponent(barcode),{cache:'no-store'});if(!r.ok)throw Error('Product lookup failed');const d=await r.json();return d}
function result(data,barcode){let p=data?.products?.[0]||data?.product||null;if(!p)throw Error('No matching product found');const existing=inv().find(i=>String(i.barcode||'').replace(/\D/g,'')===String(barcode).replace(/\D/g,''));const retail=Number(p.price||p.retail_price||0);const market=Number(p.market_price||0);const resale=market||retail*.75;const buy=resale*(getBuyPct()/100);return {p,existing,retail,market,resale,buy}}
function modal(r,barcode){document.getElementById('smartScanModal')?.remove();const o=document.createElement('div');o.id='smartScanModal';o.innerHTML=`<div class="smart-scan-card"><h2>🎮 Confirm Game</h2><p class="smart-muted">Barcode: ${esc(barcode)}</p><div class="smart-product"><strong>${esc(r.p.title||r.p.name||'Unknown title')}</strong><span>${esc(r.p.category||'Game')} ${r.p.brand?'• '+esc(r.p.brand):''}</span></div><div class="smart-prices"><div><span>Retail price</span><b>${r.retail?money(r.retail):'Not available'}</b></div><div><span>Second-hand</span><b>${r.market?money(r.market):'Not available'}</b></div><div><span>Suggested resale</span><b>${money(r.resale)}</b></div><div><span>Suggested maximum buy</span><b>${money(r.buy)}</b></div></div><label>Condition<select id="smartCondition"><option>Used - Good</option><option>Like New</option><option>Used - Fair</option><option>New</option><option>For Parts</option></select></label><div class="smart-decision"><span>Recommendation</span><strong>🟢 BUY UP TO ${money(r.buy)}</strong></div>${r.existing?`<p>📦 Already in inventory: ${esc(r.existing.name||r.p.title)} — ${Number(r.existing.quantity||0)} unit(s)</p>`:''}<div class="actions"><button class="secondary" id="smartCancel">Cancel</button><button class="primary" id="smartAdd">${r.existing?'Increase Quantity':'Add to Inventory'}</button></div></div>`;document.body.appendChild(o);document.getElementById('smartCancel').onclick=()=>o.remove();document.getElementById('smartAdd').onclick=()=>{if(r.existing){r.existing.quantity=Number(r.existing.quantity||0)+1}else{let a=inv();a.push({id:Date.now(),name:r.p.title||r.p.name||'Scanned Game',barcode,category:'Game',platform:'Other',condition:document.getElementById('smartCondition').value,quantity:1,cost:r.buy,rrp:r.retail,marketPrice:r.market,selling:r.resale,priceSource:'Barcode/Product Lookup',priceChecked:new Date().toISOString(),sales:[],dateAdded:new Date().toISOString()});localStorage.setItem('resellerInventory',JSON.stringify(a))}o.remove();alert('Item confirmed and added to inventory.')}}
window.BeauSmartScan={lookup:async barcode=>{try{const r=result(await lookup(barcode),barcode);modal(r,barcode);return r}catch(e){alert('Could not identify this barcode. You can add the item manually.')}}};
})();