/* Beau's Reseller Hub — Smart Buy + Stock Intelligence v1.5 */
(function(){'use strict';
function whole(v){return Math.round(Number(v)||0)}
function evaluate(resale,asking){const r=Number(resale)||0,a=Number(asking);const b10=whole(r*.10),b20=whole(r*.20),b25=whole(r*.25),b30=whole(r*.30),b40=whole(r*.40);if(!Number.isFinite(a)||a<0)return{status:'ENTER PRICE',className:'neutral',message:'Enter the seller’s asking price.',b10,b20,b25,b30,b40};if(a<=b25)return{status:'BUY',className:'buy',message:'Strong buy — at or below your recommended 25% target.',b10,b20,b25,b30,b40};if(a<=b30)return{status:'NEGOTIATE',className:'negotiate',message:'Potential buy — negotiate toward your 25% target.',b10,b20,b25,b30,b40};if(a<=b40)return{status:'CAUTION',className:'caution',message:'Possible buy — above 30%, but still within your 40% maximum.',b10,b20,b25,b30,b40};return{status:'PASS',className:'pass',message:'Above your 40% maximum — pass unless there is a special reason.',b10,b20,b25,b30,b40}}
function render(){const resale=document.getElementById('resale'),asking=document.getElementById('askingPrice'),out=document.getElementById('smartResult');if(!resale||!asking||!out)return;const r=Number(resale.value)||0,a=Number(asking.value);if(!r||!Number.isFinite(a)||a<0){out.innerHTML='<div class="muted">Enter an expected resale value and seller asking price.</div>';return}const d=evaluate(r,a),profit=whole(r-a);out.innerHTML=`<div class="list-item"><span>Decision</span><b>${d.status}</b></div><div class="list-item"><span>Seller asking</span><b>$${whole(a)}</b></div><div class="list-item"><span>10% minimum target</span><b>$${d.b10}</b></div><div class="list-item"><span>20% target</span><b>$${d.b20}</b></div><div class="list-item"><span>25% recommended</span><b>$${d.b25}</b></div><div class="list-item"><span>30% target</span><b>$${d.b30}</b></div><div class="list-item"><span>40% maximum</span><b>$${d.b40}</b></div><div class="list-item"><span>Potential gross profit</span><b>$${profit}</b></div><p class="muted">${d.message}</p>`}
function readInventory(){try{const x=JSON.parse(localStorage.getItem('resellerInventory')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function pct(x){const market=Number(x.market||x.sell||0),cost=Number(x.cost);return market>0&&Number.isFinite(cost)?Math.round(cost/market*100):null}
function deal(p){if(p===null)return'NO MARKET PRICE';if(p<=25)return'GREAT DEAL';if(p<=30)return'GOOD DEAL';if(p<=40)return'CAUTION';return'OVER 40%'}
function ageDays(x){const d=x.dateAdded||x.datePurchased||x.createdAt;if(!d)return null;const t=Date.parse(d);return Number.isFinite(t)?Math.max(0,Math.floor((Date.now()-t)/86400000)):null}
function attention(x,p){const a=[];if(!String(x.barcode||'').trim())a.push('Missing barcode');if(String(x.cost??'').trim()==='')a.push('Missing purchase price');if(p===null)a.push('Missing market price');if(p!==null&&p>40)a.push('Over 40%');if(p!==null&&Number(x.sell||x.market||0)<=Number(x.cost||0))a.push('No projected profit');return a}
function intelligence(){const inv=readInventory(),rows=inv.map(x=>{const q=Math.max(1,Number(x.qty)||1),cost=Number(x.cost)||0,market=Number(x.market||x.sell)||0,p=pct(x),age=ageDays(x);return{item:x,name:x.name||'Unnamed Game',cost:cost*q,sales:market*q,profit:(market-cost)*q,p,age,issues:attention(x,p)}}),capital=rows.reduce((s,x)=>s+x.cost,0),sales=rows.reduce((s,x)=>s+x.sales,0),profit=sales-capital,over=rows.filter(x=>x.p!==null&&x.p>40).length,great=rows.filter(x=>x.p!==null&&x.p<=25).length,needs=rows.filter(x=>x.issues.length),best=rows.filter(x=>x.p!==null).sort((a,b)=>a.p-b.p).slice(0,5),sellFirst=rows.filter(x=>x.sales>0).sort((a,b)=>{const scoreA=a.profit*2+(a.age??0)*3-(a.cost*.1),scoreB=b.profit*2+(b.age??0)*3-(b.cost*.1);return scoreB-scoreA}).slice(0,5),dash=document.getElementById('dashboard');if(!dash)return;let card=document.getElementById('stockIntelCard');if(!card){card=document.createElement('div');card.id='stockIntelCard';card.className='card';dash.appendChild(card)}card.innerHTML=`<h2>📊 Stock Intelligence</h2><div class="stats"><div class="stat"><span>CAPITAL</span><strong>$${whole(capital)}</strong></div><div class="stat"><span>POTENTIAL PROFIT</span><strong>$${whole(profit)}</strong></div><div class="stat"><span>GREAT DEALS</span><strong>${great}</strong></div><div class="stat"><span>OVER 40%</span><strong>${over}</strong></div></div><div class="result"><div class="list-item"><span>Potential sales value</span><b>$${whole(sales)}</b></div><div class="list-item"><span>Stock needing attention</span><b>${needs.length}</b></div></div><h3>🚨 Needs Attention</h3>${needs.length?needs.slice(0,6).map(x=>`<div class="list-item"><div><b>${esc(x.name)}</b><div class="muted">${x.issues.join(' · ')}</div></div><b>${x.p===null?'—':x.p+'%'}</b></div>`).join(''):'<div class="empty">🎉 Nothing needs attention right now.</div>'}<h3>🏆 Best Buys</h3>${best.length?best.map(x=>`<div class="list-item"><div><b>${esc(x.name)}</b><div class="muted">${x.p}% of market · ${deal(x.p)}</div></div><b>$${whole(x.profit)}</b></div>`).join(''):'<div class="empty">Add stock to see your best buys.</div>'}<h3>💸 What Should I Sell First?</h3>${sellFirst.length?sellFirst.map((x,i)=>`<div class="list-item"><div><b>${i+1}. ${esc(x.name)}</b><div class="muted">${x.age===null?'Age not recorded':x.age+' days old'} · ${x.p===null?'No market %':x.p+'% of market'}</div></div><b>$${whole(x.profit)} profit</b></div>`).join(''):'<div class="empty">Add priced stock to get a sell-first ranking.</div>'}`}
window.BeauSmartBuy={evaluate,render,version:'1.5.0',buyRange:{min:10,max:40}};window.BeauStockIntelligence={render:intelligence,version:'1.2.0'};
window.addEventListener('DOMContentLoaded',()=>{const b=document.getElementById('smartBuyBtn');if(b)b.addEventListener('click',render);const r=document.getElementById('resale'),a=document.getElementById('askingPrice');if(r)r.addEventListener('input',render);if(a)a.addEventListener('input',render);intelligence();document.querySelectorAll('.bottom button').forEach(b=>b.addEventListener('click',()=>setTimeout(intelligence,0)));window.addEventListener('storage',intelligence)});
})();
