/* Beau's Reseller Hub — Stock Watch 1.3 + Profit Intelligence + Sales + Settings Repair */
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>'$'+Math.round(Number(v)||0);
function data(){try{const x=JSON.parse(localStorage.getItem('resellerInventory')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function sales(){try{const x=JSON.parse(localStorage.getItem('beauSalesHistory')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveSales(x){localStorage.setItem('beauSalesHistory',JSON.stringify(x))}
function age(x){const raw=x.dateAdded||x.addedAt;const t=raw?new Date(raw).getTime():Date.now();return Math.max(0,(Date.now()-t)/86400000)}
function normal(x){const q=Math.max(1,Number(x.qty||x.quantity)||1),cost=Number(x.cost)||0,sell=Number(x.sell||x.market||x.selling||0);return {...x,q,cost,sell,invested:cost*q,revenue:sell*q,profit:(sell-cost)*q,pct:sell>0?Math.round(cost/sell*100):null,days:Math.round(age(x))}}
function renderWatch(all){const d=document.getElementById('dashboard');if(!d)return;let box=document.getElementById('stockWatchBox');if(!box){box=document.createElement('div');box.id='stockWatchBox';box.className='card';d.appendChild(box)}const alerts=[];all.forEach(x=>{if(x.cost<=0)alerts.push({x,reason:'Purchase price missing',level:'Cost'});else if(!x.sell)alerts.push({x,reason:'Missing resale price',level:'Pricing'});else if(x.pct>40)alerts.push({x,reason:`Bought at ${x.pct}% — above 40% maximum`,level:'Buy price'});else if(x.profit<=0)alerts.push({x,reason:'No projected gross profit',level:'Profit'});else if(x.days>=60)alerts.push({x,reason:`${x.days} days in stock`,level:'Age'});else if(x.days>=30)alerts.push({x,reason:`${x.days} days in stock`,level:'Watch'})});box.innerHTML='<h2>👀 Stock Watch</h2><div class="muted">Items that need pricing, buying-price, profit or age attention.</div>'+(alerts.length?alerts.sort((a,b)=>['Cost','Pricing','Buy price','Profit','Age','Watch'].indexOf(a.level)-['Cost','Pricing','Buy price','Profit','Age','Watch'].indexOf(b.level)).slice(0,6).map(o=>`<div class="list-item"><div><b>${esc(o.x.name||'Unnamed item')}</b><div class="muted">${esc(o.reason)} · ${esc(o.level)}</div></div><button class="btn" onclick="show('inventory');setTimeout(()=>{const q=document.getElementById('invSearch');if(q){q.value=${JSON.stringify(String(o.x.name||''))};q.dispatchEvent(new Event('input'))}},0)">View</button></div>`).join(''):'<div class="empty">✓ No stock needs attention right now.</div>')}
function renderProfit(all){const d=document.getElementById('dashboard');if(!d)return;let box=document.getElementById('profitIntelBox');if(!box){box=document.createElement('div');box.id='profitIntelBox';box.className='card';d.appendChild(box)}const priced=all.filter(x=>x.sell>0),invested=priced.reduce((s,x)=>s+x.invested,0),revenue=priced.reduce((s,x)=>s+x.revenue,0),profit=priced.reduce((s,x)=>s+x.profit,0);box.innerHTML='<h2>📈 Profit Intelligence</h2><div class="muted">Projected gross performance from your current priced stock.</div><div class="stats"><div class="stat"><span>INVESTED</span><strong>'+money(invested)+'</strong></div><div class="stat"><span>SALES</span><strong>'+money(revenue)+'</strong></div><div class="stat"><span>GROSS PROFIT</span><strong>'+money(profit)+'</strong></div></div>'+(priced.length?'<h3>🏆 Highest projected profit</h3>'+priced.slice().sort((a,b)=>b.profit-a.profit).slice(0,5).map(x=>'<div class="list-item"><div><b>'+esc(x.name||'Unnamed item')+'</b><div class="muted">'+x.q+' unit'+(x.q===1?'':'s')+' · Invested '+money(x.invested)+'</div></div><div><b>+'+money(x.profit)+'</b><br><button class="btn success" onclick="recordSaleById('+JSON.stringify(String(x.id||''))+')">Sell</button></div></div>').join(''):'<div class="empty">Add stock with a market or selling price to see projected profit.</div>')}
function recordSaleById(id){const all=data();const x=all.find(v=>String(v.id)===String(id));if(!x){alert('Stock item not found.');return}const available=Math.max(1,Number(x.qty||x.quantity)||1);const qtyText=prompt(`How many units of ${x.name||'this item'} sold? (Available: ${available})`,'1');if(qtyText===null)return;const qty=Math.floor(Number(qtyText));if(!Number.isFinite(qty)||qty<1||qty>available){alert('Enter a valid quantity from 1 to '+available+'.');return}const defaultPrice=Math.round(Number(x.sell||x.market||x.selling)||0);const priceText=prompt('Actual sale price per unit ($):',String(defaultPrice));if(priceText===null)return;const price=Number(priceText);if(!Number.isFinite(price)||price<0){alert('Enter a valid sale price.');return}const cost=Number(x.cost)||0;const sale={id:String(Date.now()),stockId:String(x.id||''),name:x.name||'Unnamed item',barcode:x.barcode||'',platform:x.platform||'',quantity:qty,costPerUnit:Math.round(cost),salePricePerUnit:Math.round(price),revenue:Math.round(price*qty),costTotal:Math.round(cost*qty),profit:Math.round((price-cost)*qty),date:new Date().toISOString()};const h=sales();h.push(sale);saveSales(h);const remaining=available-qty;if(remaining<=0){const next=all.filter(v=>String(v.id)!==String(x.id));localStorage.setItem('resellerInventory',JSON.stringify(next))}else{const next=all.map(v=>String(v.id)===String(x.id)?{...v,qty:remaining}:v);localStorage.setItem('resellerInventory',JSON.stringify(next))}alert(`Sale recorded. Gross profit: ${money(sale.profit)}`);if(typeof window.renderAll==='function')window.renderAll();render()}
function renderSales(){const d=document.getElementById('dashboard');if(!d)return;let box=document.getElementById('salesIntelBox');if(!box){box=document.createElement('div');box.id='salesIntelBox';box.className='card';d.appendChild(box)}const h=sales();const revenue=h.reduce((s,x)=>s+(Number(x.revenue)||0),0),cost=h.reduce((s,x)=>s+(Number(x.costTotal)||0),0),profit=h.reduce((s,x)=>s+(Number(x.profit)||0),0),units=h.reduce((s,x)=>s+(Number(x.quantity)||0),0);box.innerHTML='<h2>💵 Sales History</h2><div class="muted">Actual completed sales — no fees or postage included.</div><div class="stats"><div class="stat"><span>UNITS SOLD</span><strong>'+units+'</strong></div><div class="stat"><span>REVENUE</span><strong>'+money(revenue)+'</strong></div><div class="stat"><span>ACTUAL PROFIT</span><strong>'+money(profit)+'</strong></div></div>'+(h.length?h.slice().reverse().slice(0,8).map(x=>'<div class="list-item"><div><b>'+esc(x.name)+'</b><div class="muted">'+x.quantity+' unit'+(x.quantity===1?'':'s')+' · '+new Date(x.date).toLocaleDateString('en-AU')+'</div></div><div><b>'+money(x.revenue)+'</b><div class="muted">Profit '+money(x.profit)+'</div></div></div>').join(''):'<div class="empty">No completed sales yet.</div>')}
function render(){const all=data().map(normal);renderWatch(all);renderProfit(all);renderSales()}
window.recordSaleById=recordSaleById;
function repairSettings(){
  const importFile=document.getElementById('importFile');
  const check=document.getElementById('checkUpdate');
  if(importFile&&!importFile.dataset.repairBound){importFile.dataset.repairBound='1';importFile.addEventListener('change',e=>{const file=e.target.files&&e.target.files[0];if(file)window.importBackup(file);e.target.value=''})}
  if(check&&!check.dataset.repairBound){check.dataset.repairBound='1';check.addEventListener('click',window.checkUpdate||checkUpdatesRepair)}
}
function exportRepair(){const payload={version:'9.2.2',exportedAt:new Date().toISOString(),inventory:data(),library:(()=>{try{const x=JSON.parse(localStorage.getItem('beauGameLibrary')||'[]');return Array.isArray(x)?x:[]}catch{return[]}})(),sales:sales()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='beau-reseller-backup.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);if(typeof window.toast==='function')window.toast('Backup exported')}
function importRepair(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d||typeof d!=='object')throw Error();if(!Array.isArray(d.inventory)&&!Array.isArray(d.library)&&!Array.isArray(d.sales))throw Error();if(Array.isArray(d.inventory))localStorage.setItem('resellerInventory',JSON.stringify(d.inventory));if(Array.isArray(d.library))localStorage.setItem('beauGameLibrary',JSON.stringify(d.library));if(Array.isArray(d.sales))localStorage.setItem('beauSalesHistory',JSON.stringify(d.sales));if(typeof window.loadData==='function')window.loadData();render();if(typeof window.toast==='function')window.toast('Backup restored successfully')}catch{if(typeof window.toast==='function')window.toast('Invalid backup file')}};r.readAsText(file)}
function checkUpdatesRepair(){const box=document.getElementById('updateBox');if(!box)return;box.innerHTML='Checking for updates…';fetch('./update.json?ts='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(d=>{const current='9.2.2',available=String(d.version||current);const parts=v=>v.replace(/^v/i,'').split('.').map(n=>parseInt(n,10)||0);const a=parts(available),b=parts(current);let cmp=0;for(let i=0;i<3;i++){if(a[i]!==b[i]){cmp=a[i]-b[i];break}}if(cmp>0)box.innerHTML='<b>Current app:</b> '+current+'<br><b>Available:</b> '+esc(available)+'<br><span class="muted">'+esc(d.message||'A newer stable release is available.')+'</span><div class="toolbar"><button class="btn primary" onclick="location.href=\'./ota.html?ts='+Date.now()+'\'">Install latest update</button></div>';else box.innerHTML='<b>Current app:</b> '+current+'<br><b>Available:</b> '+esc(available)+'<br><span class="muted">You are on the latest stable version.</span><div class="toolbar"><button class="btn success" disabled>✓ Up to date</button></div>'}).catch(e=>{box.innerHTML='<span class="muted">Update check failed: '+esc(e.message||'Unable to reach update service.')+'</span>'})}
window.exportBackup=exportRepair;window.importBackup=importRepair;window.checkUpdate=checkUpdatesRepair;
function boot(){render();repairSettings();const old=window.renderDashboard;window.renderDashboard=function(){if(typeof old==='function')old();render()};window.addEventListener('storage',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden){repairSettings();render()}})}
window.addEventListener('DOMContentLoaded',boot);
})();
