/* Beau's Reseller Hub — Stock Watch 1.1 + Profit Intelligence */
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>'$'+Math.round(Number(v)||0);
function data(){try{const x=JSON.parse(localStorage.getItem('resellerInventory')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function age(x){const raw=x.dateAdded||x.addedAt;const t=raw?new Date(raw).getTime():Date.now();return Math.max(0,(Date.now()-t)/86400000)}
function normal(x){const q=Math.max(1,Number(x.qty||x.quantity)||1),cost=Number(x.cost)||0,sell=Number(x.sell||x.market||x.selling||0);return {...x,q,cost,sell,invested:cost*q,revenue:sell*q,profit:(sell-cost)*q,pct:sell>0?Math.round(cost/sell*100):null,days:Math.round(age(x))}}
function renderWatch(all){const d=document.getElementById('dashboard');if(!d)return;let box=document.getElementById('stockWatchBox');if(!box){box=document.createElement('div');box.id='stockWatchBox';box.className='card';d.appendChild(box)}const alerts=[];all.forEach(x=>{if(x.cost<=0)alerts.push({x,reason:'Purchase price missing',level:'Cost'});else if(!x.sell)alerts.push({x,reason:'Missing resale price',level:'Pricing'});else if(x.pct>40)alerts.push({x,reason:`Bought at ${x.pct}% — above 40% maximum`,level:'Buy price'});else if(x.profit<=0)alerts.push({x,reason:'No projected gross profit',level:'Profit'});else if(x.days>=60)alerts.push({x,reason:`${x.days} days in stock`,level:'Age'});else if(x.days>=30)alerts.push({x,reason:`${x.days} days in stock`,level:'Watch'})});
box.innerHTML='<h2>👀 Stock Watch</h2><div class="muted">Items that need pricing, buying-price, profit or age attention.</div>'+(alerts.length?alerts.sort((a,b)=>['Cost','Pricing','Buy price','Profit','Age','Watch'].indexOf(a.level)-['Cost','Pricing','Buy price','Profit','Age','Watch'].indexOf(b.level)).slice(0,6).map(o=>`<div class="list-item"><div><b>${esc(o.x.name||'Unnamed item')}</b><div class="muted">${esc(o.reason)} · ${esc(o.level)}</div></div><button class="btn" onclick="show('inventory');setTimeout(()=>{const q=document.getElementById('invSearch');if(q){q.value=${JSON.stringify(String(o.x.name||''))};q.dispatchEvent(new Event('input'))}},0)">View</button></div>`).join(''):'<div class="empty">✓ No stock needs attention right now.</div>')}
function renderProfit(all){const d=document.getElementById('dashboard');if(!d)return;let box=document.getElementById('profitIntelBox');if(!box){box=document.createElement('div');box.id='profitIntelBox';box.className='card';d.appendChild(box)}const priced=all.filter(x=>x.sell>0),invested=priced.reduce((s,x)=>s+x.invested,0),revenue=priced.reduce((s,x)=>s+x.revenue,0),profit=priced.reduce((s,x)=>s+x.profit,0);box.innerHTML='<h2>📈 Profit Intelligence</h2><div class="muted">Projected gross performance from your current priced stock.</div><div class="stats"><div class="stat"><span>INVESTED</span><strong>'+money(invested)+'</strong></div><div class="stat"><span>SALES</span><strong>'+money(revenue)+'</strong></div><div class="stat"><span>GROSS PROFIT</span><strong>'+money(profit)+'</strong></div></div>'+(priced.length?'<h3>🏆 Highest projected profit</h3>'+priced.slice().sort((a,b)=>b.profit-a.profit).slice(0,5).map(x=>'<div class="list-item"><div><b>'+esc(x.name||'Unnamed item')+'</b><div class="muted">'+x.q+' unit'+(x.q===1?'':'s')+' · Invested '+money(x.invested)+'</div></div><b>+'+money(x.profit)+'</b></div>').join(''):'<div class="empty">Add stock with a market or selling price to see projected profit.</div>')}
function render(){const all=data().map(normal);renderWatch(all);renderProfit(all)}
function boot(){render();const old=window.renderDashboard;window.renderDashboard=function(){if(typeof old==='function')old();render()};window.addEventListener('storage',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()})}
window.addEventListener('DOMContentLoaded',boot);
})();
