/* Stock & Games unified view 1.0 */
(function(){'use strict';
let filter='all';
const esc2=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money2=v=>'$'+Math.round(Number(v)||0);
function getInv(){try{const x=JSON.parse(localStorage.getItem('resellerInventory')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function getLib(){try{const x=JSON.parse(localStorage.getItem('beauGameLibrary')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveInv(x){localStorage.setItem('resellerInventory',JSON.stringify(x))}
function unified(){const inv=getInv(), lib=getLib(), owned=new Set(inv.map(x=>String(x.barcode||'')).filter(Boolean));const saved=lib.filter(x=>!owned.has(String(x.barcode||''))).map(x=>({id:'lib:'+String(x.barcode||x.title),name:x.title||'Unnamed Game',barcode:x.barcode||'',platform:x.platform||'Other',condition:'Saved Game',qty:0,cost:0,market:Number(x.resale)||0,sell:Number(x.resale)||0,saved:true,library:x}));return inv.map(x=>({...x,saved:false})).concat(saved)}
function render(){const box=document.getElementById('invList'),search=document.getElementById('invSearch');if(!box)return;const q=String(search?.value||'').toLowerCase().trim();let rows=unified().filter(x=>{if(filter==='owned'&&x.saved)return false;if(filter==='saved'&&!x.saved)return false;return `${x.name} ${x.barcode} ${x.platform}`.toLowerCase().includes(q)});box.innerHTML=rows.length?rows.map(x=>{const p=x.market>0&&x.cost>0?Math.round(x.cost/x.market*100):null;const status=x.saved?'SAVED':'IN STOCK';const deal=p===null?'NO MARKET PRICE':p<=25?'GREAT DEAL':p<=30?'GOOD DEAL':p<=40?'CAUTION':'OVER 40%';return `<div class="list-item"><div><b>${esc2(x.name)}</b><div><span class="pill">${esc2(x.platform)}</span><span class="pill">${status}</span>${x.saved?'':`<span class="pill">Qty ${Number(x.qty)||1}</span>`}</div><div class="muted">Barcode ${esc2(x.barcode||'—')} · ${x.saved?'Resale '+money2(x.market):'Cost '+money2(x.cost)+' · Sell '+money2(x.sell)}</div><div class="muted">${x.saved?'Saved from Game Library':deal}</div></div><div class="toolbar">${x.saved?`<button class="btn success" onclick="stockSavedGame(${JSON.stringify(x.library).replace(/"/g,'&quot;')})">＋ Add to Stock</button>`:`<button class="btn" onclick="editInventory('${esc2(x.id)}')">Edit</button> <button class="btn danger" onclick="deleteInventory('${esc2(x.id)}')">Delete</button>`}</div></div>`}).join(''):'<div class="empty">No games match your search.</div>';document.getElementById('stockFilterAll')?.classList.toggle('primary',filter==='all');document.getElementById('stockFilterOwned')?.classList.toggle('primary',filter==='owned');document.getElementById('stockFilterSaved')?.classList.toggle('primary',filter==='saved')}
window.stockSavedGame=function(x){if(!x)return;openInventoryEdit({name:x.title||'',barcode:x.barcode||'',platform:x.platform||'Other',condition:'Used - Good',qty:1,cost:'',market:Math.round(Number(x.resale)||0),sell:Math.round(Number(x.resale)||0)});if(typeof toast==='function')toast('Enter your purchase price before saving')};
window.renderInventory=render;
function init(){document.getElementById('stockFilterAll')?.addEventListener('click',()=>{filter='all';render()});document.getElementById('stockFilterOwned')?.addEventListener('click',()=>{filter='owned';render()});document.getElementById('stockFilterSaved')?.addEventListener('click',()=>{filter='saved';render()});document.getElementById('invSearch')?.addEventListener('input',render);render()}
window.addEventListener('DOMContentLoaded',init);
})();
