/* Stock & Games unified view 1.2 — inventory + sales + profit analytics */
(function(){'use strict';
let filter='all';
const salesKey='beauSalesHistory';
const esc2=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money2=v=>'$'+Math.round(Number(v)||0);
function getInv(){try{const x=JSON.parse(localStorage.getItem('resellerInventory')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function getLib(){try{const x=JSON.parse(localStorage.getItem('beauGameLibrary')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function getSales(){try{const x=JSON.parse(localStorage.getItem(salesKey)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveInv(x){localStorage.setItem('resellerInventory',JSON.stringify(x))}
function unified(){const inv=getInv(),lib=getLib(),owned=new Set(inv.map(x=>String(x.barcode||'')).filter(Boolean));const saved=lib.filter(x=>!owned.has(String(x.barcode||''))).map(x=>({id:'lib:'+String(x.barcode||x.title),name:x.title||'Unnamed Game',barcode:x.barcode||'',platform:x.platform||'Other',condition:'Saved Game',qty:0,cost:0,market:Number(x.resale)||0,sell:Number(x.resale)||0,saved:true,library:x}));return inv.map(x=>({...x,saved:false})).concat(saved)}
function render(){const box=document.getElementById('invList'),search=document.getElementById('invSearch');if(!box)return;const q=String(search?.value||'').toLowerCase().trim();let rows=unified().filter(x=>{if(filter==='owned'&&x.saved)return false;if(filter==='saved'&&!x.saved)return false;return `${x.name} ${x.barcode} ${x.platform}`.toLowerCase().includes(q)});box.innerHTML=rows.length?rows.map(x=>{const p=x.market>0&&x.cost>0?Math.round(x.cost/x.market*100):null;const status=x.saved?'SAVED':'IN STOCK';const deal=p===null?'NO MARKET PRICE':p<=25?'GREAT DEAL':p<=30?'GOOD DEAL':p<=40?'CAUTION':'OVER 40%';return `<div class="list-item"><div><b>${esc2(x.name)}</b><div><span class="pill">${esc2(x.platform)}</span><span class="pill">${status}</span>${x.saved?'':`<span class="pill">Qty ${Number(x.qty)||1}</span>`}</div><div class="muted">Barcode ${esc2(x.barcode||'—')} · ${x.saved?'Resale '+money2(x.market):'Cost '+money2(x.cost)+' · Sell '+money2(x.sell)}</div><div class="muted">${x.saved?'Saved from Game Library':deal}</div></div><div class="toolbar">${x.saved?`<button class="btn success" onclick="stockSavedGame(${JSON.stringify(x.library).replace(/"/g,'&quot;')})">＋ Add to Stock</button>`:`<button class="btn success" onclick="recordStockSale('${esc2(x.id)}')">💵 Sell</button><button class="btn" onclick="editInventory('${esc2(x.id)}')">Edit</button> <button class="btn danger" onclick="deleteInventory('${esc2(x.id)}')">Delete</button>`}</div></div>`}).join(''):'<div class="empty">No games match your search.</div>';document.getElementById('stockFilterAll')?.classList.toggle('primary',filter==='all');document.getElementById('stockFilterOwned')?.classList.toggle('primary',filter==='owned');document.getElementById('stockFilterSaved')?.classList.toggle('primary',filter==='saved')}
window.stockSavedGame=function(x){if(!x)return;openInventoryEdit({name:x.title||'',barcode:x.barcode||'',platform:x.platform||'Other',condition:'Used - Good',qty:1,cost:'',market:Math.round(Number(x.resale)||0),sell:Math.round(Number(x.resale)||0)});if(typeof toast==='function')toast('Enter your purchase price before saving')};
window.recordStockSale=function(id){const a=getInv(),x=a.find(v=>String(v.id)===String(id));if(!x){if(typeof toast==='function')toast('Stock item not found');return}const available=Math.max(1,Number(x.qty)||1),q=prompt(`Units sold for ${x.name||'this game'}? Available: ${available}`,'1');if(q===null)return;const qty=Math.floor(Number(q));if(!Number.isFinite(qty)||qty<1||qty>available){alert('Enter a valid quantity.');return}const suggested=Math.round(Number(x.sell||x.market)||0),p=prompt('Actual sale price per unit ($):',String(suggested));if(p===null)return;const price=Number(p),cost=Number(x.cost)||0;if(!Number.isFinite(price)||price<0){alert('Enter a valid sale price.');return}const sale={id:String(Date.now()),stockId:String(x.id),name:x.name||'Unnamed Game',barcode:x.barcode||'',platform:x.platform||'',quantity:qty,cost:cost*qty,revenue:price*qty,profit:(price-cost)*qty,date:new Date().toISOString()};const h=getSales();h.push(sale);localStorage.setItem(salesKey,JSON.stringify(h));const remaining=available-qty;if(remaining<=0)saveInv(a.filter(v=>String(v.id)!==String(x.id)));else saveInv(a.map(v=>String(v.id)===String(x.id)?{...v,qty:remaining}:v));if(typeof window.loadData==='function')window.loadData();if(typeof window.renderAll==='function')window.renderAll();renderSales();if(typeof toast==='function')toast('Sale recorded — profit '+money2(sale.profit))};
function renderSales(){const d=document.getElementById('dashboard');if(!d)return;let box=document.getElementById('salesTrackerBox');if(!box){box=document.createElement('div');box.id='salesTrackerBox';box.className='card';d.appendChild(box)}const h=getSales(),revenue=h.reduce((s,x)=>s+(Number(x.revenue)||0),0),cost=h.reduce((s,x)=>s+(Number(x.cost)||0),0),profit=h.reduce((s,x)=>s+(Number(x.profit)||0),0),units=h.reduce((s,x)=>s+(Number(x.quantity)||0),0),avg=units?Math.round(profit/units):0;box.innerHTML='<h2>💵 Sales & Profit</h2><div class="muted">Actual completed sales.</div><div class="stats"><div class="stat"><span>UNITS SOLD</span><strong>'+units+'</strong></div><div class="stat"><span>REVENUE</span><strong>'+money2(revenue)+'</strong></div><div class="stat"><span>PROFIT</span><strong>'+money2(profit)+'</strong></div><div class="stat"><span>AVG PROFIT</span><strong>'+money2(avg)+'</strong></div></div>'+(h.length?h.slice().reverse().slice(0,5).map(x=>'<div class="list-item"><div><b>'+esc2(x.name||'Unnamed Game')+'</b><div class="muted">'+Number(x.quantity||1)+' unit'+(Number(x.quantity||1)===1?'':'s')+' · '+new Date(x.date).toLocaleDateString('en-AU')+'</div></div><div><b>'+money2(x.revenue)+'</b><div class="muted">Profit '+money2(x.profit)+'</div></div></div>').join(''):'<div class="empty">No completed sales yet. Use Sell from Stock & Games.</div>')}
window.renderInventory=render;
function init(){document.getElementById('stockFilterAll')?.addEventListener('click',()=>{filter='all';render()});document.getElementById('stockFilterOwned')?.addEventListener('click',()=>{filter='owned';render()});document.getElementById('stockFilterSaved')?.addEventListener('click',()=>{filter='saved';render()});document.getElementById('invSearch')?.addEventListener('input',render);render();renderSales()}
window.addEventListener('DOMContentLoaded',init);
})();
